# Generated by Django 5.2.1 on 2025-08-23 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_batches', models.IntegerField(default=0)),
                ('open_batches', models.IntegerField(default=0)),
                ('closed_batches', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('completed_items', models.IntegerField(default=0)),
                ('pending_items', models.IntegerField(default=0)),
                ('over_stock_items', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('avg_pick_time', models.FloatField(default=0, help_text='Average time to pick item in seconds')),
                ('avg_scan_time', models.FloatField(default=0, help_text='Average time to scan barcode in seconds')),
                ('total_scans', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('critical_errors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_f_date_e00edf_idx'), models.Index(fields=['total_batches'], name='analytics_f_total_b_a91724_idx'), models.Index(fields=['completed_items'], name='analytics_f_complet_c5639e_idx')],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_usage', models.FloatField(help_text='CPU usage percentage')),
                ('memory_usage', models.FloatField(help_text='Memory usage percentage')),
                ('disk_usage', models.FloatField(help_text='Disk usage percentage')),
                ('db_connections', models.IntegerField(default=0)),
                ('db_query_time', models.FloatField(default=0, help_text='Average query time in seconds')),
                ('active_sessions', models.IntegerField(default=0)),
                ('request_queue_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='HEALTHY', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_s_timesta_652f92_idx'), models.Index(fields=['status'], name='analytics_s_status_e7a067_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='ERROR', max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('exception_type', models.CharField(blank=True, max_length=100, null=True)),
                ('exception_message', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', '-timestamp'], name='analytics_e_level_94b0d5_idx'), models.Index(fields=['timestamp'], name='analytics_e_timesta_df942d_idx'), models.Index(fields=['resolved'], name='analytics_e_resolve_bc454a_idx'), models.Index(fields=['exception_type'], name='analytics_e_excepti_31ae41_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10)),
                ('request_path', models.CharField(max_length=500)),
                ('request_size', models.IntegerField(default=0)),
                ('response_status', models.IntegerField()),
                ('response_size', models.IntegerField(default=0)),
                ('load_time', models.FloatField(help_text='Time in seconds')),
                ('response_time', models.FloatField(help_text='Time in seconds')),
                ('database_queries', models.IntegerField(default=0)),
                ('database_time', models.FloatField(default=0, help_text='Database query time in seconds')),
                ('memory_usage', models.IntegerField(default=0, help_text='Memory usage in bytes')),
                ('cpu_usage', models.FloatField(default=0, help_text='CPU usage percentage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_p_timesta_d77605_idx'), models.Index(fields=['request_path'], name='analytics_p_request_19ac26_idx'), models.Index(fields=['response_status'], name='analytics_p_respons_83afce_idx'), models.Index(fields=['load_time'], name='analytics_p_load_ti_87492c_idx'), models.Index(fields=['request_method', 'request_path'], name='analytics_p_request_98fe90_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SCAN_BARCODE', 'Scan Barcode'), ('UPDATE_QUANTITY', 'Update Quantity'), ('UPLOAD_PHOTO', 'Upload Photo'), ('CREATE_BATCH', 'Create Batch'), ('CLOSE_BATCH', 'Close Batch'), ('VIEW_DASHBOARD', 'View Dashboard'), ('EXPORT_DATA', 'Export Data'), ('IMPORT_DATA', 'Import Data'), ('DELETE_ITEM', 'Delete Item'), ('EDIT_ITEM', 'Edit Item')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='analytics_u_user_id_428695_idx'), models.Index(fields=['action', '-timestamp'], name='analytics_u_action_52ac4a_idx'), models.Index(fields=['timestamp'], name='analytics_u_timesta_412843_idx'), models.Index(fields=['success'], name='analytics_u_success_01d1ee_idx')],
            },
        ),
    ]
