# Generated by Django 5.2.1 on 2025-06-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_productimporthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_batch', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status_batch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('jumlah_ambil', models.IntegerField(default=0)),
                ('status_ambil', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('batchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fullfilment.batchlist')),
            ],
        ),
    ]
