# Generated by Django 5.2.1 on 2025-06-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0001_initial'),
        ('products', '0002_productimporthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
