# Generated by Django 5.2.1 on 2025-06-07 03:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0002_alter_batchitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('filter_params', models.JSONField()),
                ('orders', models.JSONField()),
            ],
        ),
    ]
