# Generated by Django 5.2.1 on 2025-06-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0003_filteredorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_pesanan', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('export_time', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
