# Generated by Django 5.2.1 on 2025-06-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0004_exportedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchlist',
            name='status_batch',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
