# Generated by Django 5.2.1 on 2025-06-09 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0005_alter_batchlist_status_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyToPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pesanan', models.CharField(max_length=100)),
                ('status_print', models.CharField(default='pending', max_length=20)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('batchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullfilment.batchlist')),
            ],
        ),
    ]
