# Generated by Django 5.2.1 on 2025-06-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0006_readytoprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='readytoprint',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readytoprint',
            name='order_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
