# Generated by Django 5.2.1 on 2025-06-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0007_readytoprint_brand_readytoprint_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchlist',
            name='status_batch',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('closed', 'Closed')], default='pending', max_length=50),
        ),
    ]
