# Generated by Django 5.2.1 on 2025-06-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0008_alter_batchlist_status_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readytoprint',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='readytoprint',
            name='order_type',
        ),
    ]
