# Generated by Django 5.2.1 on 2025-06-20 12:10

from django.db import migrations, models


def update_batch_status(apps, schema_editor):
    BatchList = apps.get_model('fullfilment', 'BatchList')
    # Update semua batch dengan status 'pending' menjadi 'open'
    BatchList.objects.filter(status_batch='pending').update(status_batch='open')
    # Update semua batch dengan status 'completed' menjadi 'closed'
    BatchList.objects.filter(status_batch='completed').update(status_batch='closed')


def reverse_update_batch_status(apps, schema_editor):
    BatchList = apps.get_model('fullfilment', 'BatchList')
    # Reverse: update 'open' kembali ke 'pending'
    BatchList.objects.filter(status_batch='open').update(status_batch='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0008_alter_batchlist_status_batch'),
    ]

    operations = [
        # Data migration untuk mengubah status yang ada
        migrations.RunPython(update_batch_status, reverse_update_batch_status),
        
        # Schema migration untuk mengubah choices
        migrations.AlterField(
            model_name='batchlist',
            name='status_batch',
            field=models.CharField(
                choices=[('open', 'Open'), ('closed', 'Closed')],
                default='open',
                max_length=50
            ),
        ),
    ] 