# Generated by Django 5.2.1 on 2025-06-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0009_remove_readytoprint_brand_and_more'),
        ('fullfilment', '0009_update_batchlist_status'),
    ]

    operations = [
    ]
