# Generated by Django 5.2.1 on 2025-06-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0010_merge_20250624_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='batchlist',
            name='status_batch',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('closed', 'Closed')], default='pending', max_length=50),
        ),
    ]
