# Generated by Django 5.2.1 on 2025-06-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0011_batchitem_completed_at_batchitem_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='duo_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='one_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='tri_count',
            field=models.IntegerField(default=0),
        ),
    ]
