# Generated by Django 5.2.1 on 2025-06-26 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0012_batchitem_duo_count_batchitem_one_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersCheckingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pesanan', models.CharField(db_index=True, max_length=100)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('barcode_scanned', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders Checking Histories',
                'ordering': ['-scan_time'],
            },
        ),
    ]
