# Generated by Django 5.2.1 on 2025-06-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0013_orderscheckinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlist',
            name='status_pengambilan',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='batchlist',
            name='status_batch',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=50),
        ),
    ]
