# Generated by Django 5.2.1 on 2025-06-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0014_batchlist_status_pengambilan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchlist',
            name='status_pengambilan',
        ),
        migrations.AlterField(
            model_name='batchlist',
            name='status_batch',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('closed', 'Closed')], default='pending', max_length=50),
        ),
    ]
