# Generated by Django 5.2.1 on 2025-06-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0015_remove_batchlist_status_pengambilan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchlist',
            name='status_batch',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='pending', max_length=50),
        ),
    ]
