# Generated by Django 5.2.1 on 2025-07-01 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0016_alter_batchlist_status_batch'),
        ('products', '0005_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
