# Generated by Django 5.2.2 on 2025-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0019_batchitemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitemlog',
            name='jumlah_input',
            field=models.IntegerField(default=1),
        ),
    ]
