# Generated by Django 5.2.2 on 2025-07-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0020_batchitemlog_jumlah_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='readytoprint',
            name='handed_over_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Diserahkan'),
        ),
    ]
