# Generated by Django 5.2.2 on 2025-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0021_readytoprint_handed_over_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='readytoprint',
            name='printed_via',
            field=models.CharField(blank=True, help_text='Metode pencetakan (e.g., SAT, PRIO, MIX)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='readytoprint',
            name='handed_over_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
