# Generated by Django 5.2.2 on 2025-07-09 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0022_readytoprint_printed_via_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readytoprint',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readytoprint',
            name='batchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_to_print_items', to='fullfilment.batchlist'),
        ),
    ]
