# Generated by Django 5.2.2 on 2025-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0023_readytoprint_printed_by_alter_readytoprint_batchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='readytoprint',
            name='copied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
