# Generated by Django 5.2.2 on 2025-07-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0024_readytoprint_copied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlist',
            name='close_count',
            field=models.IntegerField(default=0, help_text='Jumlah kali batch ini di-close'),
        ),
    ]
