# Generated by Django 5.2.2 on 2025-07-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0025_batchlist_close_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='jumlah_transfer',
            field=models.IntegerField(default=0),
        ),
    ]
