# Generated by Django 5.2.2 on 2025-07-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0026_batchitem_jumlah_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='jumlah_terpakai',
            field=models.IntegerField(default=0),
        ),
    ]
