# Generated by Django 5.2.2 on 2025-07-22 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0027_batchitem_jumlah_terpakai'),
        ('products', '0008_productaddhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='readytoprint',
            name='id_pesanan',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='BatchOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action_type', models.CharField(choices=[('CANCEL', 'Cancel Order'), ('ERASE', 'Erase from Batch'), ('TRANSFER', 'Transfer Batch')], db_index=True, max_length=10)),
                ('id_pesanan', models.CharField(db_index=True, max_length=255)),
                ('sku', models.CharField(help_text='Denormalized SKU for history', max_length=100)),
                ('product_name', models.CharField(blank=True, help_text='Denormalized product name', max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, help_text='Alasan atau detail tambahan', null=True)),
                ('batch_destination', models.ForeignKey(blank=True, help_text='Batch tujuan (khusus transfer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_logs', to='fullfilment.batchlist')),
                ('batch_source', models.ForeignKey(help_text='Batch asal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_logs', to='fullfilment.batchlist')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Order Log',
                'verbose_name_plural': 'Batch Order Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
