# Generated by Django 5.2.2 on 2025-07-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0028_alter_readytoprint_id_pesanan_batchorderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='jumlah_keep',
            field=models.IntegerField(default=0),
        ),
    ]
