# Generated by Django 5.2.2 on 2025-07-29 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0029_batchitem_jumlah_keep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id_scanned', models.CharField(db_index=True, help_text='ID Pesanan atau AWB yang discan', max_length=255)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('status_pembayaran_at_scan', models.CharField(blank=True, help_text='Status Pembayaran Order saat discan', max_length=50, null=True)),
                ('status_fulfillment_at_scan', models.CharField(blank=True, help_text='Status Fulfillment Order saat discan', max_length=50, null=True)),
                ('status_retur', models.CharField(default='N', help_text='Status retur: N=Belum diproses, Y=Sudah diproses retur', max_length=1)),
                ('user', models.ForeignKey(blank=True, help_text='User yang melakukan scan', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Cancel Log',
                'verbose_name_plural': 'Order Cancel Logs',
                'ordering': ['-scan_time'],
            },
        ),
    ]
