# Generated by Django 5.2.2 on 2025-07-31 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0030_ordercancellog'),
        ('products', '0008_productaddhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('sumber', models.CharField(choices=[('overstock_batch', 'Overstock Batch'), ('order_cancel', 'Order Cancel')], max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch_asal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fullfilment.batchlist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_return', models.PositiveIntegerField(default=0)),
                ('qty_scanned', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('last_scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('returnlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fullfilment.returnlist')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('barcode', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('returnitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanlogs', to='fullfilment.returnstockitem')),
            ],
        ),
    ]
