# Generated by Django 5.2.2 on 2025-08-01 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0031_returnlist_returnstockitem_returnscanlog'),
        ('products', '0008_productaddhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnstockitem',
            name='returnlist',
        ),
        migrations.RemoveField(
            model_name='returnstockitem',
            name='last_scanned_by',
        ),
        migrations.RemoveField(
            model_name='returnstockitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='returnscanlog',
            name='returnitem',
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_target', models.PositiveIntegerField(default=0)),
                ('qty_scanned', models.PositiveIntegerField(default=0)),
                ('qc_status', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Passed QC'), ('fail', 'Failed QC')], default='pending', max_length=10)),
                ('qc_notes', models.TextField(blank=True, null=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='returnscanlog',
            name='return_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanlogs', to='fullfilment.returnitem'),
        ),
        migrations.CreateModel(
            name='ReturnSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('qc_done', 'QC Done'), ('validated', 'Validated'), ('closed', 'Closed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='returnitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fullfilment.returnsession'),
        ),
        migrations.CreateModel(
            name='ReturnSourceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fullfilment.batchlist')),
                ('return_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='fullfilment.returnitem')),
            ],
        ),
        migrations.DeleteModel(
            name='ReturnList',
        ),
        migrations.DeleteModel(
            name='ReturnStockItem',
        ),
    ]
