# Generated by Django 5.2.2 on 2025-08-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0032_remove_returnstockitem_returnlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnsourcelog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_logs', to='fullfilment.returnsession'),
        ),
    ]
