# Generated by Django 5.2.2 on 2025-08-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0033_returnsourcelog_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnitem',
            old_name='qty_target',
            new_name='qty',
        ),
    ]
