# Generated by Django 5.2.2 on 2025-08-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0035_returnsourcelog_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportedOrder',
        ),
        migrations.DeleteModel(
            name='FilteredOrders',
        ),
    ]
