# Generated by Django 5.2.2 on 2025-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0036_delete_exportedorder_delete_filteredorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='putaway_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='putaway_status',
            field=models.CharField(choices=[('pending', 'Pending Putaway'), ('ready_for_putaway', 'Ready for Putaway'), ('putaway_in_progress', 'Putaway In Progress'), ('completed', 'Putaway Completed')], default='pending', max_length=20),
        ),
    ]
