# Generated by Django 5.2.2 on 2025-08-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0037_returnitem_putaway_notes_returnitem_putaway_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnsession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('qc_done', 'QC Done'), ('ready_for_putaway', 'Ready for Putaway'), ('putaway_in_progress', 'Putaway In Progress'), ('validated', 'Validated'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
