# Generated by Django 5.2.2 on 2025-08-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0038_alter_returnsession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='putaway_notes',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='putaway_status',
        ),
        migrations.AlterField(
            model_name='returnsession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
