# Generated by Django 5.2.2 on 2025-08-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0039_simplify_returnsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='putaway_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='qty_putaway',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
