# Generated by Django 5.2.1 on 2025-08-23 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0040_add_putaway_fields_to_returnitem'),
        ('products', '0014_add_database_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batchitem',
            index=models.Index(fields=['batchlist'], name='fullfilment_batchli_b80882_idx'),
        ),
        migrations.AddIndex(
            model_name='batchitem',
            index=models.Index(fields=['product'], name='fullfilment_product_c9fb98_idx'),
        ),
        migrations.AddIndex(
            model_name='batchitem',
            index=models.Index(fields=['status_ambil'], name='fullfilment_status__026e62_idx'),
        ),
        migrations.AddIndex(
            model_name='batchitem',
            index=models.Index(fields=['last_updated'], name='fullfilment_last_up_773b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='batchitem',
            index=models.Index(fields=['batchlist', 'status_ambil'], name='fullfilment_batchli_04d6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='batchitem',
            index=models.Index(fields=['product', 'batchlist'], name='fullfilment_product_7f5b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='batchitem',
            index=models.Index(fields=['batchlist', 'last_updated'], name='fullfilment_batchli_30d36d_idx'),
        ),
    ]
