# Generated by Django 5.2.2 on 2025-08-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0041_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='batchitem',
            name='fullfilment_batchli_b80882_idx',
        ),
        migrations.RemoveIndex(
            model_name='batchitem',
            name='fullfilment_product_c9fb98_idx',
        ),
        migrations.RemoveIndex(
            model_name='batchitem',
            name='fullfilment_status__026e62_idx',
        ),
        migrations.RemoveIndex(
            model_name='batchitem',
            name='fullfilment_last_up_773b7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='batchitem',
            name='fullfilment_batchli_04d6bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='batchitem',
            name='fullfilment_product_7f5b5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='batchitem',
            name='fullfilment_batchli_30d36d_idx',
        ),
    ]
