# Generated by Django 5.2.1 on 2025-09-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0042_remove_batchitem_fullfilment_batchli_b80882_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanPacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Scan Packing', max_length=100)),
            ],
            options={
                'verbose_name': 'Scan Packing',
                'verbose_name_plural': 'Scan Packing',
                'permissions': [('can_view_scanpacking', 'Can view scan packing'), ('can_add_scanpacking', 'Can add scan packing'), ('can_change_scanpacking', 'Can change scan packing'), ('can_delete_scanpacking', 'Can delete scan packing')],
            },
        ),
        migrations.CreateModel(
            name='ScanPicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Scan Picking', max_length=100)),
            ],
            options={
                'verbose_name': 'Scan Picking',
                'verbose_name_plural': 'Scan Picking',
                'permissions': [('can_view_scanpicking', 'Can view scan picking'), ('can_add_scanpicking', 'Can add scan picking'), ('can_change_scanpicking', 'Can change scan picking'), ('can_delete_scanpicking', 'Can delete scan picking')],
            },
        ),
        migrations.CreateModel(
            name='ScanShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Scan Shipping', max_length=100)),
            ],
            options={
                'verbose_name': 'Scan Shipping',
                'verbose_name_plural': 'Scan Shipping',
                'permissions': [('can_view_scanshipping', 'Can view scan shipping'), ('can_add_scanshipping', 'Can add scan shipping'), ('can_change_scanshipping', 'Can change scan shipping'), ('can_delete_scanshipping', 'Can delete scan shipping')],
            },
        ),
    ]
