# Generated by Django 5.2.1 on 2025-09-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0043_scanpacking_scanpicking_scanshipping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScanPacking',
        ),
        migrations.DeleteModel(
            name='ScanPicking',
        ),
        migrations.DeleteModel(
            name='ScanShipping',
        ),
        migrations.AlterModelOptions(
            name='batchlist',
            options={'permissions': [('can_view_scanpicking', 'Can view scan picking'), ('can_view_scanpacking', 'Can view scan packing'), ('can_view_scanshipping', 'Can view scan shipping')]},
        ),
    ]
