# Generated by Django 5.2.1 on 2025-09-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0044_delete_scanpacking_delete_scanpicking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchlist',
            options={},
        ),
    ]
