# Generated by Django 5.2.1 on 2025-09-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0045_alter_batchlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchitem',
            options={'default_permissions': ()},
        ),
    ]
