# Generated by Django 5.2.2 on 2025-09-28 17:01

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType


def remove_batchitem_permissions(apps, schema_editor):
    """Remove default permissions for BatchItem model"""
    try:
        # Get the ContentType for BatchItem
        content_type = ContentType.objects.get(
            app_label='fullfilment',
            model='batchitem'
        )
        
        # Remove all permissions for this content type
        Permission.objects.filter(content_type=content_type).delete()
        
        print(f"Removed permissions for fullfilment.batchitem")
    except ContentType.DoesNotExist:
        print("ContentType for fullfilment.batchitem not found")


def reverse_remove_batchitem_permissions(apps, schema_editor):
    """Reverse operation - recreate permissions"""
    # This is a no-op since we can't easily recreate the exact permissions
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0046_alter_batchitem_options'),
    ]

    operations = [
        migrations.RunPython(
            remove_batchitem_permissions,
            reverse_remove_batchitem_permissions
        ),
    ]
