# Generated by Django 5.2.2 on 2025-09-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0047_auto_20250929_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='batchlist',
            options={'permissions': [('view_shipping_module', 'Can access shipping module (scanshipping + order-shipping-list)'), ('view_packing_module', 'Can access packing module (scanpacking + order-packing-list)'), ('view_picking_module', 'Can access picking module (scanpicking + order-checking-list)')], 'verbose_name': 'Batch List', 'verbose_name_plural': 'Batch Lists'},
        ),
    ]
