# Generated by Django 5.2.1 on 2025-10-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0048_alter_batchitem_options_alter_batchlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchlist',
            options={'permissions': [('view_shipping_module', 'Can access shipping module (scanshipping + order-shipping-list)'), ('view_packing_module', 'Can access packing module (scanpacking + order-packing-list)'), ('view_picking_module', 'Can access picking module (scanpicking + order-checking-list)'), ('generate_batch', 'Can create new batch (generate batch)'), ('edit_batchlist', 'Can edit batchlist (start picking, ready to print, transfer, close, clean, delete)'), ('view_batchlist_detail', 'Can view batchlist details (SKU gantung, return stock links)')], 'verbose_name': 'Batch List', 'verbose_name_plural': 'Batch Lists'},
        ),
    ]
