# Generated by Django 5.2.1 on 2025-10-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0051_alter_batchlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchlist',
            options={'permissions': [('view_shipping_module', 'Can access shipping module (scanshipping + order-shipping-list)'), ('view_packing_module', 'Can access packing module (scanpacking + order-packing-list)'), ('view_picking_module', 'Can access picking module (scanpicking + order-checking-list)'), ('view_batchpicking', 'Can access batchpicking module'), ('view_generatebatch', 'Can view generate batch page'), ('change_generatebatch', 'Can perform actions on generate batch (filter, clear, check stock, generate batchlist)'), ('generate_batch', 'Can generate batch and access printed list')], 'verbose_name': 'Batch List', 'verbose_name_plural': 'Batch Lists'},
        ),
    ]
