# Generated by Django 5.2.1 on 2025-10-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0056_alter_batchlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchlist',
            options={'permissions': [('view_shipping_module', 'Can access shipping module (scanshipping + order-shipping-list)'), ('view_packing_module', 'Can access packing module (scanpacking + order-packing-list)'), ('view_picking_module', 'Can access picking module (scanpicking + order-checking-list)'), ('view_desktop_batchpicking', 'Can access desktop batchpicking module'), ('view_mobile_batchpicking', 'Can access mobile batchpicking module'), ('view_desktop_batchlist', 'Can view desktop batch list'), ('view_mobile_batchlist', 'Can view mobile batch list'), ('view_readytoprint', 'Can access readytoprint module'), ('view_generatebatch', 'Can view generate batch page'), ('change_generatebatch', 'Can perform actions on generate batch (filter, clear, check stock, generate batchlist)'), ('generate_batch', 'Can generate batch and access printed list'), ('view_returnlist', 'Can access return list module')], 'verbose_name': 'Batch List', 'verbose_name_plural': 'Batch Lists'},
        ),
    ]
