# Generated by Django 5.2.1 on 2025-10-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0057_alter_batchlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchlist',
            options={'permissions': [('view_desktop_shipping_module', 'Can access desktop shipping module (scanshipping + order-shipping-list)'), ('view_desktop_packing_module', 'Can access desktop packing module (scanpacking + order-packing-list)'), ('view_desktop_picking_module', 'Can access desktop picking module (scanpicking + order-checking-list)'), ('view_desktop_batchpicking', 'Can access desktop batchpicking module'), ('view_desktop_batchlist', 'Can view desktop batch list'), ('view_desktop_readytoprint', 'Can access desktop readytoprint module'), ('view_desktop_generatebatch', 'Can view desktop generate batch page'), ('change_desktop_generatebatch', 'Can perform actions on desktop generate batch (filter, clear, check stock, generate batchlist)'), ('generate_desktop_batch', 'Can generate desktop batch and access printed list'), ('view_desktop_returnlist', 'Can access desktop return list module'), ('view_mobile_shipping_module', 'Can access mobile shipping module (scanshipping + order-shipping-list)'), ('view_mobile_packing_module', 'Can access mobile packing module (scanpacking + order-packing-list)'), ('view_mobile_picking_module', 'Can access mobile picking module (scanpicking + order-checking-list)'), ('view_mobile_batchpicking', 'Can access mobile batchpicking module'), ('view_mobile_batchlist', 'Can view mobile batch list'), ('view_mobile_readytoprint', 'Can access mobile readytoprint module'), ('view_mobile_generatebatch', 'Can view mobile generate batch page'), ('change_mobile_generatebatch', 'Can perform actions on mobile generate batch (filter, clear, check stock, generate batchlist)'), ('generate_mobile_batch', 'Can generate mobile batch and access printed list'), ('view_mobile_returnlist', 'Can access mobile return list module'), ('view_shipping_module', 'Can access shipping module (scanshipping + order-shipping-list)'), ('view_packing_module', 'Can access packing module (scanpacking + order-packing-list)'), ('view_picking_module', 'Can access picking module (scanpicking + order-checking-list)'), ('view_readytoprint', 'Can access readytoprint module'), ('view_generatebatch', 'Can view generate batch page'), ('change_generatebatch', 'Can perform actions on generate batch (filter, clear, check stock, generate batchlist)'), ('generate_batch', 'Can generate batch and access printed list'), ('view_returnlist', 'Can access return list module')], 'verbose_name': 'Batch List', 'verbose_name_plural': 'Batch Lists'},
        ),
    ]
