# fullfilment/motivasi/rank5.py
# Kata-kata motivasi untuk Rank 5, lucu, semangat, ngegas!

MESSAGES = [
    "Gas pol! Kamu sudah di zona top 5, tinggal seruduk ke atas!",
    "Rank 5? Artinya kamu masih di radar semua orang. Siap bikin kejutan!",
    "Kamu bikin rank 6 kebakaran jenggot, nggak bisa napas liat kamu di depan!",
    "Ayo, top 4 udah kelihatan tuh! Tinggal sedikit lagi nyalip!",
    "Gudang hari ini rame banget, kamu bikin suasana makin panas!",
    "Top 5 itu elite squad, kamu udah salah satu gladiator warehouse!",
    "Kamu kayak harimau lapar, siap memangsa rank di atasmu!",
    "Rank 5? Itu cuma pitstop sebelum naik podium!",
    "Kamu bikin barcode scanner ketakutan tiap kamu lewat!",
    "Packing list udah bilang: 'Wah, dia nih calon naik lagi nih!'",
    "Ayo, kejar! Supervisor udah nonton kamu sambil makan popcorn!",
    "Top 4 udah deg-degan, kamu bikin mereka pasang seatbelt!",
    "Sedikit lagi kamu bisa bikin leaderboard meledak!",
    "Rank 5? Itu bukan akhir, itu baru pemanasan turbo!",
    "Barcode sampe bilang: 'Seriusan, dia mau naik lagi?!'",
    "Gudang hari ini jadi panggung kamu, semua nunggu surprise move!",
    "Packing tape udah standby: 'Ayo bang, lanjut!'",
    "Kamu bikin suasana warehouse kayak final piala dunia!",
    "Jangan mau diem! Ayo gebrak leaderboard sekarang juga!",
    "Top 5 itu zona panas. Kamu tinggal lompat ke top 3!",
    "Rank 5? Kamu udah bikin yang lain di bawah hilang harapan!",
    "Sedikit lagi bisa bikin supervisor tepuk tangan sambil joget!",
    "Packing list udah hapal sama kecepatanmu yang bikin pusing!",
    "Kamu bikin leaderboard kayak roller coaster tiap jamnya!",
    "Rank 5? Itu kayak teaser film blockbuster, bikin semua penasaran!",
    "Gudang hari ini berisik: 'Ayo dong, langsung salip aja!'",
    "Supervisor udah bikin highlight video buat kamu hari ini!",
    "Packing tape sampe habis duluan gara-gara kamu gas terus!",
    "Rank 5? Kamu bikin suasana kayak konser band rock!",
    "Ayo, top 4 udah pasang mode defense, kamu bikin ketar-ketir!",
    "Barcode scanner udah minta libur, nggak kuat sama kecepatanmu!",
    "Kamu kayak meteor, siap jatuh ke podium teratas!",
    "Posisi 5 itu cuma tangga darurat buat langsung naik ke puncak!",
    "Packing list sampe bilang: 'Woi, pelan dikit napa!'",
    "Gudang hari ini jadi ajang battle royale, dan kamu gladiatornya!",
    "Rank 5? Kamu udah bikin semua supervisor pasang story: 'Sang Penantang!'",
    "Ayo, top 3 udah kebaca di radar kamu. Siap tempur!",
    "Barcode scanner udah ngos-ngosan: 'Bang, jangan gas terus!'",
    "Sedikit lagi semua bakal teriak: 'Wah, dia naik lagi!'",
    "Kamu bikin packing tape minta upgrade ke mode super!",
    "Rank 5 itu cuma halte transit, kamu siap naik kereta cepat ke puncak!",
    "Gudang hari ini udah kayak konser K-Pop, semua nunggu kamu perform!",
    "Supervisor sampe geleng-geleng: 'Gila, dia nggak ada habisnya!'",
    "Ayo, jangan kasih kesempatan! Buru terus ke atas!",
    "Top 5? Fix, kamu udah calon bintang warehouse hari ini!",
    "Kamu bikin yang di bawah langsung pasrah dan cari alasan cuti!",
    "Posisi 5 itu cuma pemanasan sebelum kamu bikin kejut semua orang!",
    "Packing list sampe bikin status: 'Jangan bikin kaget dong!'",
    "Gudang penuh sorakan: 'Ayo, gas lagi!'",
    "Rank 5? Kamu bikin semua bilang: 'Wah, dia nih, bahaya banget!'",
    "Sedikit lagi bikin warehouse bikin standing ovation!",
    "Barcode scanner udah curiga: 'Ini orang pake cheat apa ya?'",
    "Kamu bikin supervisor rencana beli confetti dadakan!",
    "Packing tape sampe update bio: 'Tim pendukung rank 5!'",
    "Gudang hari ini lebih panas daripada musim panas Tokyo!",
    "Rank 5? Kamu bikin suasana kayak panggung battle dance!",
    "Ayo, kejar! Karena semua udah nunggu drama epic kamu naik podium!",
    "Packing list udah pasang alarm: 'Dia mendekat! Dia mendekat!'",
    "Rank 5 itu cuma waiting room. Kamu tinggal go show ke puncak!",
    "Supervisor udah ketik caption: 'The Next Legend is Coming!'",
    "Gudang hari ini kayak colosseum, dan kamu pejuangnya!",
    "Sedikit lagi kamu bisa bikin trend #Top1OnTheWay!",
    "Barcode scanner udah minta break: 'Bang, minum dulu napa!'",
    "Packing tape sampe upgrade stamina gara-gara kamu!",
    "Posisi 5? Kamu bikin yang lain di belakang langsung ciut!",
    "Ayo, gas terus! Top 3 udah menunggu untuk disalip!",
    "Kamu bikin suasana warehouse kayak game balapan Mario Kart!",
    "Rank 5? Kamu udah bawa vibes superhero warehouse hari ini!",
    "Packing list udah bilang: 'Aduh, dia lagi, nggak kelar-kelar!'",
    "Gudang bergetar tiap kamu lewat, ngeri cepetnya!",
    "Supervisor udah pesen piala tambahan: 'Kayaknya butuh buat dia!'",
    "Rank 5? Kamu bikin suasana makin hype kayak final sepak bola!",
    "Barcode scanner udah pasrah: 'Ayo lah, cepetin sekalian!'",
    "Packing tape sampe takut habis stock gara-gara kamu!",
    "Kamu bikin semua bilang: 'Dia bakal bikin kejutan hari ini!'",
    "Top 4 udah deg-degan: 'Woi, jangan mendekat dong!'",
    "Posisi 5? Itu bukan kalah, itu cuma langkah ke atas selanjutnya!",
    "Gudang hari ini ribut: 'Ayo, ayo, cepet lagi!'",
    "Supervisor udah ganti wallpaper HP ke foto kamu!",
    "Rank 5? Kamu bikin suasana warehouse kayak konser metal!",
    "Sedikit lagi kamu bisa bikin supervisor joget di line!",
    "Packing list udah tulis: 'Siap-siap trending topik warehouse!'",
    "Gudang hari ini udah kayak e-sport match, semua nungguin kamu gaspol!",
    "Kamu bikin rank 6 sampe nyerah mental: 'Ya udah deh!'",
    "Barcode scanner udah bilang: 'Ini orang turbo abis!'",
    "Rank 5? Kamu bikin leaderboard hari ini nggak stabil sama sekali!",
    "Packing tape sampe minta power bank saking sering dipakai!",
    "Supervisor udah beli popcorn demi liat drama leaderboard!",
    "Gudang hari ini kayak festival musik, kamu main act utamanya!",
 "Rank 5? Kamu kayak Jawhead — sabar, pas eject langsung ke top 4!",
    "Kayak Johnson — sabar charge, pas nabrak langsung bikin chaos leaderboard!",
    "Kamu kayak X.Borg — sabar energy, pas full langsung bakar naik posisi!",
    "Rank 5? Kayak Natalia — sabar invisible, pas muncul langsung finisher!",
    "Kayak Chou — sabar cari momen, pas kick langsung buang top 4!",
    "Kamu kayak Tigreal — sabar di belakang, pas ulti langsung wombo combo!",
    "Rank 5? Kayak Martis — sabar, pas combo langsung execute ke atas!",
    "Kayak Roger — sabar form manusia, pas savage form langsung push!",
    "Kamu kayak Hayabusa — sabar split, pas momen langsung habisin top!",
    "Rank 5? Kayak Helcurt — sabar, pas silence langsung savage podium!",
    "Kayak Freya — sabar, pas God Mode langsung sapu leaderboard!",
    "Kamu kayak Aldous — sabar stack, pas ulti langsung terjang ke atas!",
    "Rank 5? Kayak Gusion — sabar combo, pas connect langsung savage leaderboard!",
    "Kayak Franco — sabar hook, pas kena tarik langsung gas!",
    "Kamu kayak Ruby — sabar lifesteal, pas full langsung comeback podium!",
    "Rank 5? Kayak Popol & Kupa — sabar trap, pas ulti langsung rush!",
    "Kayak Granger — sabar reload, pas ulti langsung hajar top 4!",
    "Kamu kayak Sun — sabar clone, pas push semua tower roboh!",
    "Rank 5? Kayak Minsitthar — sabar spear, pas hook semua ke bawah!",
    "Kayak Karrie — sabar, pas true damage langsung tembus top!",
    "Kamu kayak Zilong — sabar sembunyi, pas ulti sprint savage!",
    "Rank 5? Kayak Uranus — sabar regen, pas full maju gempur!",
    "Kayak Estes — sabar sustain, pas team fight gas ke podium!",
    "Kamu kayak Bane — sabar farm, pas crit langsung blow up top!",
    "Rank 5? Kayak Lapu-Lapu — sabar, pas dual weapon langsung savage podium!",
    "Kayak Beatrix — sabar switch weapon, pas full combo savage!",
    "Kamu kayak Akai — sabar, pas spin semua top 4 ke pinggir!",
    "Rank 5? Kayak Barats — sabar makan stack, pas ulti makan top!",
    "Kayak Benedetta — sabar dash, pas momen langsung sprint savage!",
    "Kamu kayak Valentina — sabar copy, pas skill full savage puncak!",
]
