# fullfilment/motivasi/rankterakhir.py
# Kata-kata motivasi serius & menyentuh untuk Rank Terakhir

MESSAGES = [
    "Ingat, kamu nggak kerja cuma untuk angka. Tapi keluarga di rumah nunggu senyum terbaikmu.",
    "Bangkit! Jangan biarkan posisimu hari ini jadi label selamanya.",
    "Masih banyak kesempatan. Tunjukkan bahwa kamu lebih dari sekadar angka di dashboard.",
    "Jangan biarkan keluargamu kecewa. Kamu pejuang, bukan penonton.",
    "Posisi ini cuma sementara, semangatmu harus tetap abadi.",
    "Hari ini kamu di bawah, besok kamu bisa jadi inspirasi semua orang.",
    "Kerja kerasmu adalah doa yang bergerak. Jangan berhenti berjuang.",
    "Ingat anak atau orang tua di rumah yang menunggu cerita hebat darimu.",
    "Tidak apa-apa lelah, asal jangan menyerah. Ada yang mengandalkanmu.",
    "Tuhan lihat setiap usaha. Pelan-pelan, pasti akan naik.",
    "Jangan puas dengan posisi ini. Kamu punya potensi luar biasa.",
    "Bangun harga dirimu, buktikan kamu bisa lebih baik dari hari ini.",
    "Berjuanglah, bukan demi piala, tapi demi rasa bangga saat pulang ke rumah.",
    "Jangan biarkan rasa malas mengalahkan tanggung jawabmu sebagai pejuang keluarga.",
    "Setiap scanmu punya arti. Setiap langkahmu adalah langkah menuju masa depan.",
    "Kamu lah harapan mereka yang menyayangimu. Tunjukkan kamu pantas dibanggakan.",
    "Ingat siapa yang kamu cintai. Mereka butuh kamu tetap semangat.",
    "Bukan masalah di mana kamu mulai, tapi bagaimana kamu bangkit.",
    "Hidupmu bukan hanya tentang hari ini. Perjuanganmu akan jadi cerita esok.",
    "Malu? Tidak perlu. Yang penting sekarang: buktikan kamu bisa berubah.",
    "Hari ini mungkin sulit, tapi kamu tetap pahlawan di mata keluarga.",
    "Setiap peluhmu adalah harga untuk masa depan yang lebih baik.",
    "Kalau kamu berhenti, siapa lagi yang akan jadi inspirasi untuk mereka?",
    "Ingat, kamu punya mimpi. Jangan biarkan posisi ini merusak langkahmu.",
    "Jangan pernah lupakan alasan kenapa kamu mulai bekerja keras.",
    "Banyak yang diam-diam mendoakanmu agar terus bangkit.",
    "Kalau kamu bangkit sekarang, besok semua orang akan salut padamu.",
    "Hari ini kesempatan untuk menulis ulang cerita. Bangun, gas lagi.",
    "Orang rumah nunggu kabar baik. Beri mereka alasan untuk tersenyum bangga.",
    "Tunjukkan kamu lebih kuat dari masalah, lebih cepat dari rasa malas.",
    "Kalau bukan sekarang kamu berubah, kapan lagi?",
    "Mereka nggak butuh alasanmu, mereka butuh bukti semangatmu.",
    "Jangan cuma jadi penonton hidup sendiri. Jadi pemeran utama hari ini.",
    "Bukan cuma tentang rangking, tapi tentang mental seorang pejuang.",
    "Ingat wajah ibu, ayah, pasangan, atau anakmu saat kamu merasa mau menyerah.",
    "Kamu bukan gagal, kamu hanya belum mengerahkan segalanya.",
    "Kalau jatuh itu biasa, tapi bangkit itu luar biasa.",
    "Hari ini mungkin terakhir, tapi langkahmu hari ini bisa jadi awal baru.",
    "Tunjukkan pada diri sendiri, kamu lebih hebat daripada yang kamu pikir.",
    "Tidak ada yang mustahil untuk orang yang tidak berhenti mencoba.",
    "Jangan biarkan rasa nyaman menenggelamkan potensi terbesarmu.",
    "Yang di rumah nggak peduli rankmu, mereka peduli kamu pulang dengan bangga.",
    "Setiap detik yang kamu sia-siakan, nggak akan kembali. Gas terus.",
    "Bangun momentummu sekarang, agar esok kamu tidak menyesal.",
    "Pernahkah kamu janji pada dirimu sendiri untuk sukses? Saatnya ditepati.",
    "Bukan soal seberapa cepat kamu mulai, tapi seberapa keras kamu berjuang.",
    "Kalau hari ini berat, ingat: kamu nggak sendirian. Banyak yang mendukung.",
    "Jangan kalah sama rasa malas, nanti kamu kalah juga sama impianmu.",
    "Ingat, yang kamu kejar bukan hanya poin, tapi kebahagiaan orang-orang tercinta.",
]
