# fullfilment/motivasi/rank4.py
# Kata-kata motivasi untuk Rank 4, lucu, semangat, dan ngegas!

MESSAGES = [
    "Gas pol! Tinggal satu step lagi ke top 3!",
    "Jangan kasih kendor! Rank 3 udah kedengeran napasnya tuh!",
    "Woi, kamu di jalur fast lane! Siap overtake kapan aja!",
    "Sedikit lagi kamu bisa bikin top 3 keringetan!",
    "Posisi 4? Itu artinya kamu pemburu utama hari ini!",
    "Rank 4 itu udah elit, tinggal upgrade ke podium!",
    "Kamu bikin yang di atas deg-degan sambil lihat dashboard!",
    "Barcode scanner udah bilang: 'Ayo bang, masih bisa kejar!'",
    "Supervisor lagi nunggu: 'Kapan nih dia ngebut lagi?'",
    "Gas lagi! Rank 3 udah ngerasa getaran langkahmu!",
    "Posisi 4 itu zona panas, siap bikin kejutan!",
    "Kamu udah kayak harimau lapar, siap makan podium!",
    "Rank 3 lagi pasang rem darurat, takut kamu lewat!",
    "Tinggal satu push lagi, top 3 bakal kamu sapu!",
    "Kamu bikin suasana warehouse makin panas dan seru!",
    "Kalau warehouse punya reality show, kamu adalah plot twist hari ini!",
    "Rank 4? Itu cuma tempat istirahat sebelum naik podium!",
    "Packing list udah deg-degan liat skor kamu merangkak naik!",
    "Gudang hari ini kayak sirkuit F1, kamu pembalap underdog yang siap ngegas!",
    "Posisi 4? Jangan puas! Top 3 udah teriak: 'Jangan biarin dia nyusul!'",
    "Sedikit lagi kamu bisa bikin confetti di warehouse!",
    "Rank 4 = mode hunter aktif! Siap buru puncak!",
    "Kamu bikin barcode scanner ngos-ngosan, keren banget!",
    "Packing tape udah standby: 'Siap tempel piala!'",
    "Rank 3 udah mulai ngelirik ke belakang, kamu bikin trauma!",
    "Gudang udah ribut: 'Dia lagi, dia lagi!'",
    "Jangan kasih ampun! Satu swipe lagi, langsung podium!",
    "Supervisor udah siapkan banner: 'Selamat Datang di Top 3!'",
    "Kamu udah bikin yang lain di belakang hopeless total!",
    "Rank 4? Itu cuma checkpoint. Kamu bakal lanjut naik terus!",
    "Gas! Kamu bikin semua makin semangat dan terhibur!",
    "Rank 4? Kamu kayak ninja yang lagi siap lompat ke podium!",
    "Hari ini kamu bikin warehouse serasa sirkuit balap!",
    "Barcode udah curiga: 'Ini orang makan apa sih pagi ini?!'",
    "Top 3 kayaknya bakal digeser paksa sama kamu hari ini!",
    "Jangan lupa minum, karena kamu bakal bikin top 3 haus oksigen!",
    "Rank 4? Kamu udah bikin leaderboard kerasa roller coaster!",
    "Packing list udah sampe hapal namamu saking sering scan!",
    "Supervisor udah ketik status: 'Siap-siap, ada yang bakal naik podium!'",
    "Kamu kayak petir! Sedikit lagi bakal bikin kejut semua orang!",
    "Gudang hari ini nunggu momen kamu bikin overtake dramatis!",
    "Rank 3 udah standby crying towel, takut kesalip!",
    "Kamu bikin semua di belakang mikir: 'Gimana caranya ngejar dia?'",
    "Rank 4 bukan akhir, itu start turbo buat ke podium!",
    "Barcode scanner udah ngeluh: 'Bang, capek ah, tapi semangat!'",
    "Packing tape sampe nanya: 'Kapan nih dia dapet piala?'",
    "Hari ini kamu bikin supervisor nonton sambil makan popcorn!",
    "Gas pol! Kamu udah bikin warehouse kayak panggung konser!",
    "Posisi 4? Gak masalah! Kamu tetap superstar warehouse!",
    "Gudang udah panas banget nunggu kamu salip semua!",
    "Kamu kayak jet tempur! Sedikit lagi fly ke puncak!",
    "Rank 4? Kamu udah bikin suasana kayak final kejuaraan nasional!",
    "Top 3 udah berdoa: 'Semoga dia nggak makin kenceng!'",
    "Sedikit lagi, semua akan teriak: 'DIA JUARA!'",
    "Barcode scanner udah pasrah: 'Terserah deh, ayo lanjut aja!'",
    "Posisi 4 itu spesial: bikin semua tegang setiap detik!",
    "Kamu bikin semua ranking di atas mulai insecure!",
    "Packing list udah ready sambut kamu di podium!",
    "Kamu bikin suasana warehouse kayak game battle royale!",
    "Rank 4? Itu tanda: 'Ayo, bentar lagi pecah scoreboard!'",
    "Kamu udah bikin vibes warehouse kayak turnamen esport!",
    "Gas lagi, kamu bikin semua bilang: 'Woi, dia gila cepetnya!'",
    "Rank 4? Kamu bikin semua rekan kerja kehilangan harapan ngejar!",
    "Packing tape sampe habis sebelum jam makan siang gara-gara kamu!",
    "Supervisor udah booking spot foto buat kamu di papan juara!",
    "Gudang hari ini nunggu drama: 'Kapan nih dia salip?'",
    "Posisi 4 itu cuma tangga sebelum kamu naik ke atas!",
    "Kamu bikin leaderboard hari ini kayak roller coaster kereta tercepat!",
    "Top 3 udah ngelus dada: 'Hadeuh, dia deket banget!'",
    "Scanner udah minta cuti darurat, takut overload sama kamu!",
    "Packing list sampe senyum sendiri liat scan speed kamu!",
    "Rank 4? Kamu udah bikin semua ngaku: 'Dia next level banget!'",
    "Gudang hari ini kayak arena gladiator, kamu salah satu jagoannya!",
    "Rank 4? Kamu bikin suasana jadi penuh hype dan deg-degan!",
    "Packing tape sampai bikin video reaction sendiri gara-gara kamu!",
    "Supervisor udah latihan cara ngucapin selamat buat kamu!",
    "Barcode udah siap ready scan nonstop hari ini buat kamu!",
    "Rank 4 itu tiket VIP ke podium, tinggal injak gas full!",
    "Posisi 4? Nggak masalah! Kamu tetep bikin semua amazed!",
    "Kamu bikin warehouse punya drama paling seru hari ini!",
    "Rank 4? Kamu bikin semua bilang: 'Wah, tinggal satu tarikan lagi tuh!'",
    "Gudang hari ini kayak final olimpiade, semua nonton kamu!",
    "Packing list udah tulis: 'Siap-siap naik level nih orang!'",
    "Supervisor udah order medali tambahan buat kamu!",
    "Rank 4? Kamu bikin semangat warehouse naik 300%!",
    "Posisi 4? Itu cuma 'buffer' sebelum naik ke puncak!",
    "Kamu bikin semua penonton warehouse neriakin: 'Ayo gas!'",
    "Packing tape sampe habis stock demi ngejar kamu!",
    "Top 3 udah mimpi buruk dikejar kamu semalam!",
    "Kamu bikin leaderboard bergetar tiap jam!",
    "Rank 4? Kamu living legend warehouse hari ini!",
    "Packing list udah bikin chart khusus: 'Progress kamu = WOW!'",
    "Gudang hari ini penuh sorak: 'Ayo, sedikit lagi!'",
    "Scanner udah bilang: 'Gue nggak kuat, dia cepet banget!'",
    "Rank 4? Kamu bikin suasana makin panas kayak final bulutangkis!",
    "Supervisor udah pasang spanduk: 'The Next Challenger!'",
    "Posisi 4? Itu hanya panggung pemanasan, kamu siap tempur!",
    "Rank 4? Kamu kayak Zilong — sabar di semak, pas ulti langsung sprint ke atas!",
    "Kayak Sun — clone dulu, pas momen push, langsung top 3!",
    "Kamu kayak Hanzo — sabar farming, pas shadow langsung curi posisi!",
    "Rank 4? Kayak Lapu-Lapu — sabar, pas ultimate langsung double kill podium!",
    "Kayak Freya — sabar charge, pas God Mode, langsung savage podium!",
    "Kamu kayak Beatrix — banyak senjata, tinggal pilih mana yang bikin top 3 goyah!",
    "Rank 4? Kayak Lancelot — dash-dash, tinggal satu tusukan ke podium!",
    "Kayak Roger — mode manusia santai, pas serigala langsung savage!",
    "Kamu kayak Granger — sabar reload, pas ulti langsung retak leaderboard!",
    "Rank 4? Kayak Yi Sun-shin — sabar, pas skill map hack langsung finish!",
    "Kayak Bane — sabar collect gold, pas crit langsung hancur top 3!",
    "Kamu kayak Layla — sabar dulu, pas late game tembakanmu tembus podium!",
    "Rank 4? Kayak Khufra — sabar, pas bounce langsung guncang top 3!",
    "Kayak Jawhead — sabar, pas eject top 3 ke luar leaderboard!",
    "Kamu kayak Aldous — sabar stack, pas ultimate langsung sprint savage!",
    "Rank 4? Kayak Valir — sabar dorong, pas momen langsung bakar top!",
    "Kayak Atlas — sabar, pas ulti semua top 3 keangkat!",
    "Kamu kayak Moskov — sabar, pas ultimate tembus semua podium!",
    "Rank 4? Kayak Argus — sabar, pas ultimate langsung immortal sprint ke atas!",
    "Kayak Benedetta — sabar ngisi dash, pas full langsung ngebut podium!",
    "Kamu kayak Akai — sabar, pas spin langsung lempar top 3!",
    "Rank 4? Kayak Esmeralda — sabar serap semangat, pas full langsung puncak!",
    "Kayak Barats — sabar gendut, pas momen langsung makan top rank!",
    "Kamu kayak Cecilion — sabar stack, pas full langsung savage leaderboard!",
    "Rank 4? Kayak Hanabi — sabar shield, pas aktif free hit ke podium!",
    "Kayak Thamuz — sabar farming, pas momen langsung sweeping!",
    "Kamu kayak Guinevere — sabar charge, pas ulti semua top 3 mental!",
    "Rank 4? Kayak Silvanna — sabar zoning, pas ulti langsung lock top rank!",
    "Kayak Yu Zhong — sabar, pas black dragon langsung terbang ke podium!",
    "Kamu kayak Hilda — sabar roam, pas nemu momen langsung execute podium!",
]
