# fullfilment/motivasi/rank3.py
# Kata-kata motivasi untuk Rank 3, lucu, semangat, tetap beringas!

MESSAGES = [
    "Hore! Kamu di top 3! Sudah kayak podium F1, tinggal percik champagne!",
    "Posisi 3? Kamu udah bikin yang di belakang hilang harapan!",
    "Lihat tuh di depan! Tinggal ngegas dikit lagi, kamu bisa nyalip!",
    "Kamu udah bikin rank 4 dan seterusnya insecure seharian!",
    "Podium sudah di depan mata. Satu swipe barcode lagi, naik level!",
    "Kamu bikin warehouse berasa panggung konser, vibesnya hype terus!",
    "Top 3? Itu udah kayak selebriti warehouse!",
    "Kalau warehouse punya influencer, kamu salah satunya!",
    "Orang-orang di belakang udah pasrah liat kamu jauh di depan!",
    "Kamu bikin rank 1 & 2 gelisah, karena kamu udah nempel kayak odol!",
    "Posisi 3? Santuy dulu sambil lihat yang lain ngos-ngosan!",
    "Dengan gaya kamu yang santai, rank 1 dan 2 pasti mulai panik!",
    "Sebentar lagi, puncak udah manggil-manggil namamu!",
    "Kamu udah bikin barcode ngeluh: 'Aduh, dia lagi, cepet banget!'",
    "Sambil minum teh pun kamu masih di top 3. Gokil!",
    "Posisi 3 itu sweet spot, bikin yang lain kebakaran jenggot!",
    "Rank 4 lagi ngintip sambil nangis liat kamu masih di top 3!",
    "Kamu udah kayak sultan warehouse, gaya tetep santai, performa edan!",
    "Boleh sedikit flex hari ini, top 3 bukan main-main!",
    "Supervisor udah pasang poster kamu di kantor: 'Idola baru kami!'",
    "Rank 3? Fix, kamu sudah alumni tim elite warehouse!",
    "Tinggal dua lagi di depanmu, ayo sabet mereka!",
    "Semangatmu bikin warehouse berasa festival balap!",
    "Kamu udah bikin jalur tol sendiri di warehouse, gasss terus!",
    "Rank 3? Itu panggung pemanasan sebelum naik tahta!",
    "Kalau warehouse bikin hall of fame, namamu udah nongol duluan!",
    "Scanner udah pasrah liat kamu terus nempel di top 3!",
    "Packing tape udah hafal gerakanmu, cepet banget!",
    "Jangan puas dulu! Dua di depan udah mulai keringetan!",
    "Kamu bikin suasana warehouse lebih meriah daripada konser K-Pop!",
    "Top 3 = kamu sudah di kasta para dewa warehouse!",
    "Barcode scanner udah kangen kamu tiap beberapa detik!",
    "Posisi 3? Itu berarti kamu lagi manasin mesin buat nyalip!",
    "Top 3 itu zona VIP warehouse, dan kamu member setianya!",
    "Kamu bikin yang lain mikir: 'Gimana sih caranya bisa nempel terus?!'",
    "Rank 3 udah bikin supervisor mau beliin piala mini sendiri!",
    "Sedikit lagi, kamu bisa makan siang sambil bawa mahkota!",
    "Gudang udah riuh kayak sirkuit MotoGP nunggu kamu nyalip!",
    "Kalau warehouse punya panggung Idol, kamu udah dapet golden ticket!",
    "Posisi 3 itu bukan sisa, itu sinyal: 'Sebentar lagi gue naik!'",
    "Rank 3? Bikin semua yang di belakang bilang: 'Ya udah deh, bye!'",
    "Biar pun di rank 3, kamu udah superstar warehouse hari ini!",
    "Barcode scanner sampe bilang: 'Ini orang nggak capek apa?'",
    "Kamu bikin leader susah tidur, mikir strategi ngasih tantangan baru!",
    "Sedikit lagi, scanner kamu bisa dapet sertifikat loyalitas!",
    "Rank 3 itu 'danger zone' buat rank 1 & 2, karena kamu bisa naik kapan aja!",
    "Semua selir warehouse udah nyiapin banner: 'Ayo naik ke puncak!'",
    "Packing tape sampe kebas, kamu kenceng banget!",
    "Mungkin hari ini kamu sambil ngopi, besok langsung minum champagne di puncak!",
    "Scanner udah ngeluh: 'Bang, stop dulu napa, capek nih!'",
    "Kamu bikin warehouse jadi lebih hidup, semangatnya nular banget!",
    "Rank 3? Itu udah setara status selebgram warehouse!",
    "Mau makan siang? Jangan dulu! Kejar dua lagi di depan!",
    "Kamu bikin supervisor mau bikin jersey khusus: 'Team Rank 3!'",
    "Gudang berasa kayak game battle royale, kamu top 3 yang ditakuti!",
    "Kamu bikin ranking hari ini kayak roller coaster, seru banget!",
    "Posisi 3? Bukan kalah, itu cuma momen pemanasan!",
    "Kalau warehouse punya sinetron, kamu karakter utamanya!",
    "Hari ini kamu udah kayak rival bebuyutan yang selalu bikin deg-degan!",
    "Packing list sampe hafal namamu: 'Oh, dia lagi nih!'",
    "Posisi 3 = antrian sebelum kursi raja. Tunggu giliran aja!",
    "Kamu bikin yang lain bilang: 'Gila, stamina dia nggak habis-habis!'",
    "Gudang hari ini kayak ring tinju, kamu salah satu jagoannya!",
    "Sedikit lagi kamu bisa foto di podium sambil dadah ke kamera!",
    "Top 3? Fix, kamu ikon warehouse masa kini!",
    "Kamu bikin suasana warehouse penuh api semangat!",
    "Rank 3 udah bikin supervisor senyum-senyum bangga!",
    "Barcode udah trauma tiap kamu datang, saking kencengnya!",
    "Kamu bikin yang lain bilang: 'Tolong dong, stop dulu sebentar!'",
    "Panggung warehouse hari ini: kamu, dan dua calon korban di depan!",
    "Rank 3? Kamu udah bikin semua nyerah sebelum bertanding!",
    "Tanganmu udah kayak turbo machine, auto-scan terus!",
    "Supervisor udah ngebayangin kamu naik ke podium dalam waktu dekat!",
    "Rank 3 itu cuma transit. Kamu pasti siap gas ke atas!",
    "Semua orang nunggu momen 'plot twist' kamu nyalip dua di depan!",
    "Barcode scanner sampe nanya: 'Seriusan ini orang secepet itu?'",
    "Gudang hari ini kayak festival, kamu guest star utamanya!",
    "Kamu bikin rekan kerja ketakutan: 'Dia lagi, dia lagi!'",
    "Packing tape sampe bikin group chat: 'Guys, siap-siap dia lewat!'",
    "Rank 3? Kamu udah kayak senjata makan tuan buat rival di atas!",
    "Sebentar lagi leaderboard bisa langsung berubah, thanks to you!",
    "Top 3 artinya: kamu elite squad, bukan kaleng-kaleng!",
    "Semangatmu bikin selir warehouse nonton sambil makan popcorn!",
    "Supervisor udah bikin rencana surprise celebration buat kamu!",
    "Kamu bikin suasana warehouse jadi reality show live!",
    "Rank 3 bukan akhir. Itu start line baru untuk gaspol lebih kenceng!",
    "Tanganmu udah kayak cheat mode warehouse!",
    "Gudang sampe bergetar liat kecepatanmu scan!",
    "Kamu bikin seluruh shift nanya: 'Dia makan apa sih pagi ini?!'",
    "Rank 3? Kamu udah kayak superhero warehouse hari ini!",
    "Packing list pun menyerah: 'Ya udah deh, kasih dia aja semua!'",
    "Kamu bikin supervisor kehabisan kata-kata: 'Wow, wow, wow!'",
    "Top 3 hari ini = kamu bikin semua timeline warehouse meledak!",
    "Kamu udah kayak final boss di game warehouse!",
    "Rank 3? Kamu kayak Uranus — slow regen, tiba-tiba udah di depan!",
    "Kayak Belerick — sabar defense, pas counter langsung naik posisi!",
    "Kamu kayak Rafaela — sabar healing, pas timing gaspol ke atas!",
    "Rank 3? Kayak Akai — spin pelan, tiba-tiba semua terlempar!",
    "Kayak Grock — sabar di tembok, pas maju langsung unstoppable!",
    "Kamu kayak Minotaur — rage penuh, pas ulti semua mental!",
    "Rank 3? Kayak Estes — sabar support, pas team fight langsung savage!",
    "Kayak Angela — sabar nempel, pas momen bantu savage ke atas!",
    "Kamu kayak Tigreal — pas ulti, langsung tabrak dua posisi di atas!",
    "Rank 3? Kayak Gatotkaca — sabar di base, pas lompat langsung guncang!",
    "Kayak Hylos — slow tapi pasti maju ke puncak!",
    "Kamu kayak Lolita — sabar defense, pas stun langsung sweep!",
    "Rank 3? Kayak Baxia — rolling terus, pelan-pelan ke atas!",
    "Kayak Edith — mode tank sabar, pas mech form langsung savage!",
    "Kamu kayak Ruby — sabar, pas hook semua lawan ketarik!",
    "Rank 3? Kayak Khaleed — sabar charge, pas ultimate langsung masuk ke top!",
    "Kayak Phoveus — sabar, pas banyak dash langsung jump ke top!",
    "Kamu kayak X.Borg — sabar energy, pas true damage langsung bakar semua!",
    "Rank 3? Kayak Terizla — sabar nunggu momen swing ke podium!",
    "Kayak Thamuz — sabar sustain, pas ultimate langsung sweeping!",
    "Kamu kayak Minsitthar — pas spear, narik semua yang di atas ke bawah!",
    "Rank 3? Kayak Silvanna — sabar zoning, pas ultimate langsung lock puncak!",
    "Kayak Leomord — sabar tunggu kuda, pas naik langsung savage!",
    "Kamu kayak Dyrroth — sabar rage, pas abis langsung execute!",
    "Rank 3? Kayak Alpha — sabar reset, pas full combo, savage!",
    "Kayak Balmond — sabar spin, pas retribution langsung curi top!",
    "Kamu kayak Helcurt — sabar, pas sunyi langsung savage!",
    "Rank 3? Kayak Guinevere — sabar charge, pas knock up semua mental!",
    "Kayak Martis — sabar immune, pas abis langsung triple kill!",
    "Kamu kayak Hilda — sabar roam, pas ketemu langsung execute ke puncak!",
]
