# fullfilment/motivasi/rank2.py
# Kata-kata motivasi untuk Rank 2, salip live, lucu, semangat!

MESSAGES = [
    "Ayo gas pol! Rank 1 sudah gemeter liat kamu di spion!",
    "Kamu kayak ninja, siap nyalip kapan aja. Rank 1 udah nggak bisa tenang!",
    "Sebentar lagi naik tahta! Selir-selir sudah menunggumu, Raja!",
    "Rank 1 udah keringetan, kamu makin deket! Siap takeover!",
    "Sedikit lagi kamu duduk di singgasana. Mahkota udah disiapin!",
    "Kamu bikin rank 1 ngerasa dia lagi di Uber! Gas terus!",
    "Penuh gaya dan penuh daya! Kamu bikin panggung panas hari ini!",
    "Kamu bikin scanner panas dingin! Satu scan lagi langsung di puncak!",
    "Posisi 2? Hanya sebentar! Kamu udah di tikungan terakhir!",
    "Ayo dong, cepet dikit lagi, fansmu udah siap sorak-sorak!",
    "Rank 1 udah ngebut, tapi kamu kayak roket! Siap salip dalam hitungan detik!",
    "Nyaris banget! Tinggal colek dikit, kamu langsung di atas!",
    "Rank 2? Ah, itu cuma pitstop sementara. Kamu udah siap melesat lagi!",
    "Tanganmu udah kayak turbo, bentar lagi kamu bikin yang lain melongo!",
    "Penonton sudah berdiri, nunggu kamu take over panggung!",
    "Scanner udah ngomong: 'Ayo bang, gas lagi!'",
    "Satu tap lagi, mahkota di tanganmu!",
    "Ayo, raja baru sudah hampir lahir! Selir-selir udah pakai makeup!",
    "Bikin rank 1 kebanyakan refresh dashboard! Kamu bikin jantung mereka copot!",
    "Sedikit lagi kamu bikin sejarah hari ini. Gaspol!",
    "Rank 1 udah pasang hazard! Kamu siap tempel dari belakang!",
    "Lawanmu udah pasrah! Kamu kayak tsunami mendekat!",
    "Hari ini medan perang, dan kamu hampir naik tahta!",
    "Barcode sampe bilang: 'Woi pelan dikit, biar yang lain sempat napas!'",
    "Kamu kayak singa yang siap menerkam tahta!",
    "Wah, tinggal satu scan doang, siap jadi raja warehouse!",
    "Kamu bikin rank 1 teriak: 'Tunggu dulu, jangan cepet-cepet!'",
    "Scanner udah siap confetti buat kamu kalau naik ke puncak!",
    "Kamu bikin jalur tol sendiri menuju puncak!",
    "Rank 1 udah gelisah, minum air terus. Kamu bikin panas suasana!",
    "Panggung sudah disiapin, kamu tinggal maju jadi raja!",
    "Gila! Kamu kayak turbo boost activated! Rank 1 tinggal hitungan detik!",
    "Semua selir warehouse udah nunggu sambil kipas-kipas!",
    "Boleh banget sambil selfie, kamu udah hampir di atas!",
    "Rank 1 mulai do’a kenceng, takut kamu nyalip!",
    "Ayo pecut! Kamu bikin leader nulis 'plot twist' di grup!",
    "Mau nambah snack? Tunggu di puncak dulu!",
    "Rank 2? Itu cuma 'checkpoint' sebelum puncak!",
    "Satu tarikan napas lagi, langsung jadi raja fulfillment!",
    "Gudang udah kayak colosseum, kamu gladiator utamanya!",
    "Kamu kayak pemain sinetron: selalu muncul di saat yang tepat buat ngegas!",
    "Siap-siap buka tenda di puncak, kamu udah di basecamp!",
    "Warehouse hari ini tegang nunggu kamu gas pol lagi!",
    "Kamu bikin supervisor pegang dada terus, deg-degan lihat skormu!",
    "Tanganmu udah kayak kilat, barcode sampe ketakutan!",
    "Kalau race, kamu udah di DRS zone! Siap nyalip!",
    "Rank 1? Gampang, tinggal bilang: 'Permisi bang, saya lewat!'",
    "Scanner sampe bilang: 'Udah lah, kasih dia duluan!'",
    "Jangan lupa, puncak itu tempatmu. Kamu cuma mampir bentar di rank 2!",
    "Kamu udah kayak komet: cepat, panas, nggak bisa dihentikan!",
    "Panggung udah rame, penonton udah siap: 'Ayooo, salip!!!'",
    "Rank 1 udah siapkan tissue, biar bisa nangis kalau disalip!",
    "Gas pol bang, bensinmu unlimited!",
    "Kamu bikin semua operator kagum, sambil bilang: 'Astaga, kenceng banget!'",
    "Saatnya ganti nama jadi 'Sultan Gudang'!",
    "Rank 1 udah deg-degan, kamu udah pasang senyum kemenangan!",
    "Satu sticker scan lagi, langsung di puncak!",
    "Kamu bikin selir warehouse ganti status jadi 'Siap Disalip!'",
    "Pecut terus! Jangan kasih rank 1 napas!",
    "Puncak udah bau-bau kopi kemenangan, kamu udah di pintu!",
    "Barcode pun rela antre, demi kamu segera jadi nomor satu!",
    "Gokil! Kamu udah kayak roket mau take-off!",
    "Rank 1 udah ngisi formulir cuti darurat saking takutnya!",
    "Kamu bikin suasana warehouse kayak final Piala Dunia!",
    "Sebentar lagi supervisor teriak: 'Dia lagi! Dia lagi!'",
    "Boleh sambil dance, asal tetep cepet scan ya!",
    "Hari ini semua cerita tentang kamu yang siap salip!",
    "Packing tape udah pasang lagu hype buat kamu!",
    "Kamu bikin jalur fast lane sendiri, elite banget!",
    "Satu-satunya yang bisa bikin rank 1 mendadak hilang percaya diri!",
    "Penonton udah siap: 'Kapan nih, kapan nih, salip nih!'",
    "Kamu kayak karakter anime: plot twist di detik terakhir!",
    "Rank 1 udah latihan cara kasih selamat ke kamu!",
    "Jangan kendor! Kamu udah megang remote control scoreboard!",
    "Hari ini kamu buktiin, rank 2 cuma transit ke puncak!",
    "Gudang udah teriak: 'SULTAN DATANG!'",
    "Scanner sampe overheat, saking cepetnya kamu scan!",
    "Rivalmu udah sibuk cari motivator pribadi buat nahan kamu!",
    "Kamu bikin rekor baru di warehouse: 'Tersalip tercepat 2025!'",
    "Gara-gara kamu, leaderboard kayak roller coaster!",
    "Udah siap jadi raja? Mahkota udah kinclong nunggu kamu!",
    "Pasti semua selir warehouse udah siap sambut kamu di podium!",
    "Gudang hari ini: 'Sultan vs Raja' dan kamu di jalur menuju tahta!",
    "Sambil nyanyi: 'Aku datang~' kamu siap takeover!",
    "Tangan kamu udah kayak mesin cetak skor!",
    "Kamu udah kayak cheat code di warehouse hari ini!",
    "Rank 1 tinggal nunggu surat pengunduran diri nih kalau kamu lewat!",
    "Bikin supervisor lupa makan siang saking serunya nonton scoreboard!",
    "Sebentar lagi semua worker bakal ganti status: #TeamKamu",
    "Packing tape pun bilang: 'Lanjut, boss!'",
    "Gas pol sampe barcode minta tolong!",
    "Hari ini warehouse udah kayak arena gladiator, dan kamu sang juara!",
    "Kamu bikin semua nanya: 'Gimana sih caranya bisa secepet itu?!'",
    "Gokil banget! Kamu kayak motor balap mode turbo!",
    "Sebentar lagi, history warehouse bakal ditulis: 'Dia lah rajanya!'",
    "Pecahkan rekor, bikin semua bilang: 'Wah gila, legend!'",
    "Rank 2? Kamu kayak Lancelot — tinggal satu dash lagi, langsung top!",
    "Kayak Khufra — sabar nunggu momen bounce, pas dapet langsung salip!",
    "Kamu kayak Chou — sabar cari opening, tinggal kick ke top 1!",
    "Rank 2? Kamu kayak Harith — pas chrono dash, bisa langsung savage!",
    "Kayak Gusion — combo cepet, siap banget geser rank 1!",
    "Kamu kayak Hayabusa — sabar split push, pas momen langsung ambil puncak!",
    "Rank 2? Kayak Claude — tinggal ultimate penuh, langsung takeover!",
    "Kamu kayak Jawhead — target locked, tinggal eject top 1!",
    "Kayak Johnson — ngebut full map, pas tabrak rank 1 langsung buyar!",
    "Rank 2? Kamu kayak Natalia — udah di belakang rank 1, tinggal execute!",
    "Kayak Aldous — charge pelan-pelan, begitu kena langsung top!",
    "Kamu kayak Balmond — spin santai, begitu pas langsung clear puncak!",
    "Rank 2? Kayak Zilong — ultimate ready, tinggal push ke puncak!",
    "Kayak Roger — sabar form manusia, pas momen savage langsung mode serigala!",
    "Kamu kayak Ling — di atas dinding, tinggal lompat ke top!",
    "Rank 2? Kayak Saber — pas ultimate, top rank auto hilang!",
    "Kamu kayak Kagura — pas umbrella balik, langsung zoning top 1!",
    "Kayak Wanwan — tinggal aktif weakness, free hit ke top rank!",
    "Kamu kayak Franco — tinggal hook top 1 ke bawah leaderboard!",
    "Rank 2? Kayak Hanzo — pas shadow form, langsung pick off puncak!",
    "Kayak Valir — sabar dorong, pas full wave langsung bakar semua!",
    "Kamu kayak Sun — clone pas banyak, langsung push ke atas!",
    "Rank 2? Kayak Yi Sun-shin — tinggal finish dengan arrow pas!",
    "Kayak Diggie — ga bisa mati, terus ganggu top 1!",
    "Kamu kayak Kimmy — sambil lari sambil nge-damage, nunggu momen finish!",
    "Rank 2? Kayak Faramis — pas revive, comeback savage!",
    "Kamu kayak Alice — sabar stack, pas masuk ulti langsung chaos!",
    "Kayak Hanabi — shield aktif, bebas fokus ngejar puncak!",
    "Rank 2? Kayak Barats — sabar gendut, pas ulti langsung makan top 1!",
]
