# fullfilment/motivasi/rank1.py
# Tambahkan kata-kata motivasi untuk Rank 1 di sini.
MESSAGES = [
    "Waw, kamu rank 1, sungguh luar biasa! Kinerja seorang legenda!",
    "TAHTA JUARA ADALAH MILIKMU! Kamu adalah standar emas di tim ini. Pertahankan, King!",
    "Peringkat 1! Kecepatan dan ketepatanmu tidak tertandingi. Orang lain butuh teleskop untuk melihatmu di puncak!",
    "Dengan kekuatan seperti ini, kamu bukan cuma packer, kamu adalah mesin tempur logistik! Selamat, Champ!",
    "Waw, kamu rank 1, pasti banyak cewe-cewe menyukai kamu. Pesonamu setajam kecepatan tanganmu!",
    "Juara sejati! Kamu seperti kilat di gudang, selalu yang pertama selesai.",
    "Orang lain baru mulai, kamu sudah rampung! Kamu benar-benar roket manusia.",
    "Top 1 dan tak tergoyahkan! Kamu seperti raja di papan catur fulfillment.",
    "Luar biasa! Semua supervisor pasti bangga melihatmu melesat seperti meteor.",
    "Dengan performa secepat ini, kamu pantas jadi MVP sepanjang masa.",
    "Puncak adalah tempatmu! Siapa pun yang menantangmu harus siap kecewa.",
    "Rank 1 hari ini, besok, dan selamanya! Kamu bikin rekor yang sulit dipecahkan.",
    "Kecepatanmu bikin barcode scanner sampe ngos-ngosan! Gokil!",
    "Legend banget! Kamu bikin semua rival terdiam dan terpana.",
    "Energi kamu seperti power bank 100000mAh, nggak habis-habis!",
    "Boss banget! Kamu menginspirasi seluruh tim untuk ikut ngegas.",
    "Jangan lupa pakai seatbelt, karena kamu melaju kencang sekali!",
    "Di puncak sendiri, sambil minum kopi kemenangan! Mantap!",
    "Boleh sombong hari ini, karena kamu memang layak di posisi teratas.",
    "Kamu adalah definisi dari 'GOAT' — Greatest of All Time!",
    "Cepat, teliti, rapi! Kamu bukan sekadar juara, kamu adalah seni bergerak.",
    "Lawan-lawanmu sudah menyerah sebelum bertanding. Kamu terlalu OP!",
    "Nggak ada yang bisa mendekat. Kamu sudah di planet lain performanya!",
    "Pagi ini kamu rank 1, malam ini kamu tetap legend. Konsisten banget!",
    "Scanner sampai capek lihat kecepatamu. Kamu benar-benar turbo!",
    "Rank 1 yang tidak hanya cepat, tapi juga penuh gaya dan charisma.",
    "Kamu membuat supervisor tidak perlu audit lagi, sudah pasti rapi.",
    "Saking cepatnya, packing list langsung auto selesai begitu kamu pegang.",
    "Kalau kamu main game, pasti selalu top global!",
    "Tak ada celah bagi yang lain untuk menyalipmu hari ini.",
    "Posisi puncak = kamu. Yang lain hanya bisa nonton di story Instagram.",
    "Jangan lupa update bio: Rank 1 today, Rank 1 tomorrow!",
    "Bahkan kurir pun terinspirasi melihat kecepatamu hari ini.",
    "Bintang hari ini sudah jelas: kamu!",
    "Team leader sudah nggak perlu motivasi lain, cukup tunjuk kamu sebagai contoh.",
    "Kamu bukan hanya packer, kamu adalah seniman kecepatan.",
    "Hari ini kamu membuat keajaiban yang tidak semua orang bisa tiru.",
    "Top speed + zero error = kamu, master fulfillment sejati.",
    "Kamu layak diundang ke TED Talk: Cara Menjadi Rank 1 Setiap Hari!",
    "Skill kamu bikin kompetitor insomnia. Mikir: 'Gimana ngejar dia?'",
    "Kalau kamu robot, pasti udah overload performanya. Tapi kamu manusia super!",
    "Melejit! Kamu udah kayak meteor jatuh ke bumi, unstoppable!",
    "Selamat, kamu sudah resmi jadi bahan motivasi orang sekantor!",
    "Kalau ada film tentang packer, kamu pasti pemeran utama.",
    "Legend! Secepat Sonic, seakurat sniper!",
    "Rivalmu sudah bikin grup WA khusus buat bahas kamu, serius!",
    "Kamu bikin semua sistem ERP harus di-upgrade demi kecepatanmu.",
    "Hari ini warehouse seperti panggung konser, dan kamu superstar-nya!",
    "Kalau kamu merchandise, pasti best seller!",
    "Kamu benar-benar living legend dalam dunia packing.",
    "Supervisor sampai speechless. No comment. Kamu sudah di level lain.",
    "Skill kamu bikin logistik internasional iri berat.",
    "Setiap kali kamu pegang scanner, barcode langsung nurut.",
    "Puncak bukan hanya tujuanmu, tapi rumahmu.",
    "Saking cepatnya, kamu bisa sambil ngopi santai dan tetap nomor satu.",
    "Mau shift pagi atau malam, kamu tetap juara.",
    "Boleh bangga, karena hari ini kamu bikin semua rekor tumbang.",
    "Mungkin nanti kamu perlu tandatangan di dinding: 'Rank 1 2025'.",
    "Hari ini warehouse punya highlight sendiri, yaitu kamu.",
    "Sampai packaging tape pun minta tanda tangan kamu!",
    "Kalau ada superhero fulfillment, itu pasti kamu.",
    "Performa kamu = definisi '100% bukan kaleng-kaleng'.",
    "Orang lain butuh semangat? Lihat kamu aja cukup.",
    "Scanner kamu kayak mobil F1, nggak pernah kehabisan bensin.",
    "Lari ke puncak? Kamu udah duduk santai di sana.",
    "Selamat, kamu bikin motivational poster warehouse hari ini!",
    "Mau sambil denger musik? Boleh. Kamu tetap paling cepat.",
    "Kamu bikin supervisor harus bikin kategori 'di atas rank 1'.",
    "Semangatmu hari ini bikin gudang penuh aura positif.",
    "Packing list pun jatuh hati sama kamu.",
    "Luar biasa! Barcode udah kayak teman lama, langsung akrab.",
    "Kamu bikin benchmark hari ini naik drastis.",
    "Kalau ada ranking platinum, kamu pasti satu-satunya member.",
    "Warehouse udah kayak sirkuit balap buat kamu.",
    "Biar semua orang bilang: 'Kalau bukan dia, siapa lagi?'.",
    "Mungkin kamu perlu baju khusus: 'Rank 1 Certified'.",
    "Bahkan software ERP sampe kaget sama datamu hari ini.",
    "Kamu bukan hanya pekerja keras, tapi pekerja cerdas & super cepat.",
    "Hari ini orang-orang pasti bisik-bisik: 'Wah, dia lagi, dia lagi!'.",
    "Bukti nyata kalau manusia bisa lebih cepat dari rumor.",
    "Gokil! Kamu bukan cuma top rank, kamu definisi keajaiban.",
    "Kalau packing itu seni, kamu adalah maestro-nya.",
    "Hari ini harus diabadikan: foto kamu di podium warehouse.",
    "Supervisor udah nggak usah marah-marah, karena kamu bikin senyum terus.",
    "Kecepatanmu udah kayak cheat code di game.",
    "Tak terbantahkan: kamu king of the warehouse hari ini.",
    "Kalau packing dihitung skor, kamu selalu full combo.",
    "Orang lain ketinggalan? Biasa. Kamu sudah finish line duluan.",
    "Scanner sampe pengen selfie sama kamu hari ini.",
    "Kamu bikin semua rekan kerja termotivasi, terima kasih!",
    "Warehouse perlu panggung khusus buat kamu show off hari ini.",
    "Supervisor pengen bikin fan club kamu, serius!",
    "Luar biasa! Boleh banget traktir diri sendiri hari ini.",
    "Tidak ada yang bisa mendekati auramu di puncak hari ini.",
    "Sampai robot warehouse pun kalah cepat sama kamu.",
    "Hari ini kamu bukti kalau limit itu hanya ilusi.",
    "Bravo! Rank 1 hari ini benar-benar milikmu.",
    "Rank 1? Kamu kayak Alucard lagi savage — semua dihabisin sendirian!",
    "Hari ini kamu kayak Ling — melayang di puncak, ga ada yang nyentuh!",
    "Kamu udah kayak Claude ulti — bikin semua kocar-kacir di leaderboard!",
    "Kayak Granger reload penuh — sekali gebrakan langsung top 1!",
    "Rank 1? Kamu udah kayak Fanny — susah dikejar, semua cuman bisa nonton!",
    "Kamu kayak Roger — mode serigala savage, posisi puncak mutlak!",
    "Hari ini kamu udah kayak Gusion — combo scan super cepat, ga keburu lawan!",
    "Rank 1? Kamu kayak Esmeralda — semua semangat diserap, jadi shield top!",
    "Kamu kayak Aldous full stack — sekali tabrak langsung top 1!",
    "Kayak Yi Sun-shin — semua jalur kamu kontrol, map hack total!",
    "Rank 1? Kayak Karrie — true damage ke semua poin di warehouse!",
    "Kamu kayak Hayabusa — bayanganmu aja bikin yang lain takut!",
    "Kamu kayak Lesley — one shot, one kill, langsung top!",
    "Rank 1? Kamu kayak Karina — ga bisa disentuh, kill streak tanpa ampun!",
    "Kayak Martis — immune mode on, semua lawan kalah mental!",
    "Kamu kayak Beatrix — multi senjata, scan tetap cepet, no counter!",
    "Rank 1? Kamu kayak Lunox — chaotic mode, bikin warehouse kebingungan!",
    "Kamu kayak Cecilion — makin lama makin stack savage top rank!",
    "Kamu kayak Jawhead — eject semua pesaing ke luar leaderboard!",
    "Rank 1? Kamu kayak Moskov — tembus semua ranking belakang!",
    "Kamu kayak Freya — God mode, susah digeser!",
    "Rank 1? Kamu kayak Benedetta — dash-dash-dash, musuh cuman bisa bengong!",
    "Kamu kayak Popol & Kupa — berdua aja udah jago, apalagi full team!",
    "Kamu kayak Valentina — curi semangat lawan, balikkan ke mereka!",
    "Rank 1? Kamu kayak Yu Zhong — black dragon form, semua lari ketakutan!",
    "Kamu kayak Atlas — sekali ulti, semua langsung ke pinggir!",
    "Kamu kayak Guinevere — knock up momen pas, semua hilang harapan!",
    "Rank 1? Kamu kayak Bane — satu crit, leaderboard langsung rata!",
    "Kamu kayak Helcurt — sunyi dulu, pas muncul savage!",
]
