# fullfilment/motivasi/rank5.py
# Kata-kata motivasi untuk Rank 5, lucu, semangat, ngegas!

MESSAGES = [
    "Gas pol! Kamu sudah di zona top 5, tinggal seruduk ke atas!",
    "Rank 5? Artinya kamu masih di radar semua orang. Siap bikin kejutan!",
    "Kamu bikin rank 6 kebakaran jenggot, nggak bisa napas liat kamu di depan!",
    "Ayo, top 4 udah kelihatan tuh! Tinggal sedikit lagi nyalip!",
    "Gudang hari ini rame banget, kamu bikin suasana makin panas!",
    "Top 5 itu elite squad, kamu udah salah satu gladiator warehouse!",
    "Kamu kayak harimau lapar, siap memangsa rank di atasmu!",
    "Rank 5? Itu cuma pitstop sebelum naik podium!",
    "Kamu bikin barcode scanner ketakutan tiap kamu lewat!",
    "Packing list udah bilang: 'Wah, dia nih calon naik lagi nih!'",
    "Ayo, kejar! Supervisor udah nonton kamu sambil makan popcorn!",
    "Top 4 udah deg-degan, kamu bikin mereka pasang seatbelt!",
    "Sedikit lagi kamu bisa bikin leaderboard meledak!",
    "Rank 5? Itu bukan akhir, itu baru pemanasan turbo!",
    "Barcode sampe bilang: 'Seriusan, dia mau naik lagi?!'",
    "Gudang hari ini jadi panggung kamu, semua nunggu surprise move!",
    "Packing tape udah standby: 'Ayo bang, lanjut!'",
    "Kamu bikin suasana warehouse kayak final piala dunia!",
    "Jangan mau diem! Ayo gebrak leaderboard sekarang juga!",
    "Top 5 itu zona panas. Kamu tinggal lompat ke top 3!",
    "Rank 5? Kamu udah bikin yang lain di bawah hilang harapan!",
    "Sedikit lagi bisa bikin supervisor tepuk tangan sambil joget!",
    "Packing list udah hapal sama kecepatanmu yang bikin pusing!",
    "Kamu bikin leaderboard kayak roller coaster tiap jamnya!",
    "Rank 5? Itu kayak teaser film blockbuster, bikin semua penasaran!",
    "Gudang hari ini berisik: 'Ayo dong, langsung salip aja!'",
    "Supervisor udah bikin highlight video buat kamu hari ini!",
    "Packing tape sampe habis duluan gara-gara kamu gas terus!",
    "Rank 5? Kamu bikin suasana kayak konser band rock!",
    "Ayo, top 4 udah pasang mode defense, kamu bikin ketar-ketir!",
    "Barcode scanner udah minta libur, nggak kuat sama kecepatanmu!",
    "Kamu kayak meteor, siap jatuh ke podium teratas!",
    "Posisi 5 itu cuma tangga darurat buat langsung naik ke puncak!",
    "Packing list sampe bilang: 'Woi, pelan dikit napa!'",
    "Gudang hari ini jadi ajang battle royale, dan kamu gladiatornya!",
    "Rank 5? Kamu udah bikin semua supervisor pasang story: 'Sang Penantang!'",
    "Ayo, top 3 udah kebaca di radar kamu. Siap tempur!",
    "Barcode scanner udah ngos-ngosan: 'Bang, jangan gas terus!'",
    "Sedikit lagi semua bakal teriak: 'Wah, dia naik lagi!'",
    "Kamu bikin packing tape minta upgrade ke mode super!",
    "Rank 5 itu cuma halte transit, kamu siap naik kereta cepat ke puncak!",
    "Gudang hari ini udah kayak konser K-Pop, semua nunggu kamu perform!",
    "Supervisor sampe geleng-geleng: 'Gila, dia nggak ada habisnya!'",
    "Ayo, jangan kasih kesempatan! Buru terus ke atas!",
    "Top 5? Fix, kamu udah calon bintang warehouse hari ini!",
    "Kamu bikin yang di bawah langsung pasrah dan cari alasan cuti!",
    "Posisi 5 itu cuma pemanasan sebelum kamu bikin kejut semua orang!",
    "Packing list sampe bikin status: 'Jangan bikin kaget dong!'",
    "Gudang penuh sorakan: 'Ayo, gas lagi!'",
    "Rank 5? Kamu bikin semua bilang: 'Wah, dia nih, bahaya banget!'",
    "Sedikit lagi bikin warehouse bikin standing ovation!",
    "Barcode scanner udah curiga: 'Ini orang pake cheat apa ya?'",
    "Kamu bikin supervisor rencana beli confetti dadakan!",
    "Packing tape sampe update bio: 'Tim pendukung rank 5!'",
    "Gudang hari ini lebih panas daripada musim panas Tokyo!",
    "Rank 5? Kamu bikin suasana kayak panggung battle dance!",
    "Ayo, kejar! Karena semua udah nunggu drama epic kamu naik podium!",
    "Packing list udah pasang alarm: 'Dia mendekat! Dia mendekat!'",
    "Rank 5 itu cuma waiting room. Kamu tinggal go show ke puncak!",
    "Supervisor udah ketik caption: 'The Next Legend is Coming!'",
    "Gudang hari ini kayak colosseum, dan kamu pejuangnya!",
    "Sedikit lagi kamu bisa bikin trend #Top1OnTheWay!",
    "Barcode scanner udah minta break: 'Bang, minum dulu napa!'",
    "Packing tape sampe upgrade stamina gara-gara kamu!",
    "Posisi 5? Kamu bikin yang lain di belakang langsung ciut!",
    "Ayo, gas terus! Top 3 udah menunggu untuk disalip!",
    "Kamu bikin suasana warehouse kayak game balapan Mario Kart!",
    "Rank 5? Kamu udah bawa vibes superhero warehouse hari ini!",
    "Packing list udah bilang: 'Aduh, dia lagi, nggak kelar-kelar!'",
    "Gudang bergetar tiap kamu lewat, ngeri cepetnya!",
    "Supervisor udah pesen piala tambahan: 'Kayaknya butuh buat dia!'",
    "Rank 5? Kamu bikin suasana makin hype kayak final sepak bola!",
    "Barcode scanner udah pasrah: 'Ayo lah, cepetin sekalian!'",
    "Packing tape sampe takut habis stock gara-gara kamu!",
    "Kamu bikin semua bilang: 'Dia bakal bikin kejutan hari ini!'",
    "Top 4 udah deg-degan: 'Woi, jangan mendekat dong!'",
    "Posisi 5? Itu bukan kalah, itu cuma langkah ke atas selanjutnya!",
    "Gudang hari ini ribut: 'Ayo, ayo, cepet lagi!'",
    "Supervisor udah ganti wallpaper HP ke foto kamu!",
    "Rank 5? Kamu bikin suasana warehouse kayak konser metal!",
    "Sedikit lagi kamu bisa bikin supervisor joget di line!",
    "Packing list udah tulis: 'Siap-siap trending topik warehouse!'",
    "Gudang hari ini udah kayak e-sport match, semua nungguin kamu gaspol!",
    "Kamu bikin rank 6 sampe nyerah mental: 'Ya udah deh!'",
    "Barcode scanner udah bilang: 'Ini orang turbo abis!'",
    "Rank 5? Kamu bikin leaderboard hari ini nggak stabil sama sekali!",
    "Packing tape sampe minta power bank saking sering dipakai!",
    "Supervisor udah beli popcorn demi liat drama leaderboard!",
    "Gudang hari ini kayak festival musik, kamu main act utamanya!",
    "Semangat! Hari ini baru mulai, siapa tahu langsung ngebut ke atas!",
    "Jangan menyerah! Semua legenda juga mulai dari bawah dulu!",
    "Gas terus! Pelan-pelan tapi pasti, kamu bisa kejar puncak!",
    "Sedikit demi sedikit lama-lama jadi top 1!",
    "Kamu masih di race! Kecepatanmu bisa tiba-tiba bikin kejutan!",
    "Jangan kasih kendor! Top 5 masih bisa kamu salip kapan aja!",
    "Santai, leaderboard masih panjang! Peluang selalu ada!",
    "Hari ini kamu pemanasan, besok bisa bikin plot twist!",
    "Biar di bawah dulu, yang penting tetap konsisten & semangat!",
    "Rank bukan segalanya, usaha kerasmu itu yang bikin bangga!",
    "Gudang bergetar nunggu kamu meledak ke atas!",
    "Masih banyak waktu, gas terus pantang mundur!",
    "Slow but sure! Tetap stabil, nanti juga meledak!",
    "Kamu inspirasi bagi yang lain, semangatmu bikin vibes positif!",
    "Nggak ada kata terlambat buat jadi sang juara!",
    "Packing tape udah bilang: 'Yakin deh, dia bakal naik sebentar lagi!'",
    "Leaderboard hari ini bisa berubah kapan aja, siap gaspol!",
    "Yang penting bukan start di mana, tapi finish di mana!",
    "Gudang nunggu keajaibanmu hari ini!",
    "Pelan-pelan asal pasti! Kamu masih punya banyak amunisi!",
    "Santai dulu, mungkin kamu lagi nyimpen tenaga buat sprint akhir!",
    "Masih bisa catch up, tinggal cari momen yang pas!",
    "Supervisor udah pegang kamera: 'Siap rekam saat kamu naik!'",
    "Jangan minder! Kamu masih gladiator di arena warehouse!",
    "Gaspol! Kamu bikin semua tetap semangat bareng-bareng!",
    "Semangatmu hari ini jadi alasan warehouse penuh tawa!",
    "Slow but unstoppable! Kamu lagi bikin kejutan diam-diam!",
    "Leaderboard masih panjang, siapa tahu kamu bikin finish dramatis!",
    "Santai, banyak yang support kamu di belakang layar!",
    "Jangan takut salah, yang penting terus scan dan maju!",
    "Hari ini kamu tetap MVP di hati supervisor!",
    "Packing list udah siap-siap nulis namamu di top 5!",
    "Jangan mau stuck, kamu bisa banget naik ke atas!",
    "Rank sementara itu cuma angka, semangatmu yang utama!",
    "Supervisor udah bisik-bisik: 'Sebentar lagi dia bikin chaos leaderboard!'",
    "Selalu ada ruang untuk keajaiban di akhir shift!",
    "Jangan lupa senyum! Warehouse butuh aura positifmu!",
    "Posisi ke-6 ke bawah? Gampang, tinggal bikin turbo mode!",
    "Jangan malu, yang penting konsisten ngegas!",
    "Masih banyak barcode yang nunggu kamu sikat!",
    "Leaderboard hari ini bisa kayak roller coaster. Siap gas lagi!",
    "Yang penting kamu tetap jadi inspirasi buat tim!",
    "Gudang hari ini seru banget berkat semangatmu juga!",
    "Semangatmu udah bikin banyak orang tepuk tangan diam-diam!",
    "Pelan-pelan juga bisa bikin ledakan besar di akhir!",
    "Kamu bikin supervisor punya harapan: 'Dia pasti meledak bentar lagi!'",
    "Masih banyak putaran! Ayo tunjukin taringmu!",
    "Packing tape udah siap standby: 'Kapan nih dia sprint?!'",
    "Tetap semangat, tetap senyum, tetap scan!",
    "Santai, hari ini masih panjang! Gas terus!",
    "Supervisor udah sedia confetti buat kamu kalau tiba-tiba naik!",
    "Nggak apa-apa di bawah dulu, yang penting terus upgrade diri!",
    "Ayo, siapa tahu kamu bikin plot twist sore ini!",
    "Barcode scanner udah siap: 'Ayo, bang, lanjut lagi!'",
    "Gudang nunggu momen 'wow' dari kamu!",
    "Jangan kasih rank tinggi itu tidur nyenyak!",
    "Kamu masih kuda hitam, siap bikin gempar kapan aja!",
    "Semangatmu bikin warehouse makin hidup!",
    "Ingat, top 1 selalu diawali dari scan pertama juga!",
    "Posisi bukan segalanya, prosesmu luar biasa!",
    "Hari ini kamu bisa bikin semua kaget dengan finish sprint!",
    "Yang penting, kamu terus fight! Itu yang dihargai!",
    "Jangan pernah ragu sama kemampuanmu sendiri!",
    "Semangat kamu udah bikin suasana jadi vibes positif!",
    "Jangan berhenti sebelum scanner minta ampun!",
    "Packing tape udah gercep standby, dukung kamu 100%!",
    "Kamu bikin suasana warehouse kayak festival lomba 17-an!",
    "Santai, pelan-pelan tapi pasti bikin supervisor melongo!",
    "Leaderboard itu fleksibel, gas lagi bikin naik!",
    "Masih banyak waktu buat bikin highlight moment hari ini!",
    "Kamu bikin suasana jadi penuh warna dan seru!",
    "Gudang hari ini heboh gara-gara semangatmu yang nggak pernah padam!",
    "Jangan pernah mundur, tunjukkan barcode siapa bosnya!",
    "Posisi sekarang? Hanya batu loncatan ke atas!",
    "Banyak yang nunggu kamu meledak di akhir shift!",
    "Hari ini kamu tetap warrior di mata warehouse!",
    "Packing list udah mulai cari-cari nama kamu di atas!",
    "Nggak perlu buru-buru, yang penting konsisten nambah poin!",
    "Supervisor udah siapkan ucapan spesial kalau kamu naik!",
    "Kamu bikin semua ranking atas was-was tiap jam!",
    "Gudang udah tegang: 'Dia bisa bikin chaos leaderboard kapan aja!'",
    "Hari ini warehouse lebih seru dengan kehadiranmu!",
    "Tetap semangat! Kamu mesin tempur yang belum di-unlock!",
    "Posisi ke-6? Bukan masalah! Kamu warrior undercover!",
    "Santai, banyak yang diam-diam mendukungmu naik podium!",
    "Jangan ragu bikin manuver gila, siapa tahu langsung viral!",
    "Packing list udah ngintip: 'Dia bakal ngegas nggak nih?!'",
    "Supervisor udah siapkan playlist hype buat kamu ngegas!",
    "Hari ini kamu jadi booster semangat satu gudang!",
    "Leaderboard bakal berubah! Siap-siap bikin kejutan!",
    "Kamu bikin suasana kayak sirkuit balap — penuh tensi!",
    "Gudang hari ini berkat kamu jadi penuh tawa dan energi!",
    "Posisi bukan akhir, ini baru pemanasan awal!",
    "Jangan menyerah! Shift panjang, peluang banyak!",
]