# fullfilment/motivasi/rank2terakhir.py
# Kata-kata motivasi untuk Rank 2 Terakhir (serius & membangun)

MESSAGES = [
    "Kamu masih ada satu di bawahmu, tapi jangan puas di sini. Ayo bangkit!",
    "Posisi ini bukan tempat aman. Kalau diam, besok bisa jadi terakhir.",
    "Sekarang masih ada waktu untuk kejar, jangan tunggu jatuh lebih dalam.",
    "Ayo! Jangan biarkan satu langkah lagi membuatmu jadi yang paling bawah.",
    "Ingat siapa yang menunggu kamu pulang dengan bangga di rumah.",
    "Jangan terlena. Hari ini kamu bisa naik kalau mau berusaha lebih keras.",
    "Satu posisi di bawahmu bukan alasan untuk santai. Itu peringatan.",
    "Selangkah lagi ke jurang atau selangkah lagi ke kebanggaan. Kamu yang pilih.",
    "Tunjukkan bahwa kamu lebih besar dari rasa lelahmu.",
    "Hari ini masih ada kesempatan untuk memperbaiki. Gunakan sebaik mungkin.",
    "Posisi ini cuma sementara, kalau kamu mau berubah sekarang juga.",
    "Jangan biarkan rasa nyaman di zona bawah jadi kebiasaan.",
    "Ingat wajah orang yang kamu cintai sebelum kamu menyerah.",
    "Jangan kasih celah untuk alasan, kasih ruang hanya untuk tindakan.",
    "Bukan waktunya diam. Ini waktunya kamu bangkit dan fight!",
    "Kamu tidak sendiri. Banyak yang mendukungmu untuk kembali naik.",
    "Masih ada harapan, selama kamu mau bergerak sekarang juga.",
    "Buktikan pada dirimu sendiri bahwa kamu bisa lebih dari ini.",
    "Kamu sudah terlalu jauh berjuang untuk berhenti sekarang.",
    "Saat kamu mau menyerah, ingat kenapa kamu mulai.",
    "Posisi ini seharusnya jadi cambuk, bukan selimut kenyamanan.",
    "Bangun hari ini dengan semangat baru. Pintu podium selalu terbuka.",
    "Jangan sampai kamu bilang 'andai saja' besok. Mulai sekarang!",
    "Rasa malu itu datang kalau kamu diam. Kalau kamu gerak, itu jadi kebanggaan.",
    "Ada keluarga yang menunggu kabar baikmu, jangan kecewakan mereka.",
    "Kalau bukan hari ini kamu mulai, kapan lagi?",
    "Hari ini kamu diingatkan: jangan puas, terus bergerak!",
    "Kamu punya tenaga, punya mimpi, punya alasan kuat. Tunjukkan sekarang!",
    "Satu peringkat di bawahmu mungkin sedang menunggu kamu lengah.",
    "Lawan rasa malasmu, jangan biarkan mentalmu jatuh.",
    "Hari ini bukan akhir cerita. Kamu masih bisa menulis bab baru.",
    "Bangkit sekarang! Bukan besok, bukan nanti.",
    "Jangan pernah berhenti selagi kaki masih bisa melangkah.",
    "Kamu pejuang, bukan hanya pengikut. Buktikan!",
    "Mundur satu langkah, lawan! Naikkan semangatmu dua kali lipat.",
    "Jangan biarkan kebiasaan lama merusak masa depanmu.",
    "Hari ini kesempatan, besok hanya penyesalan kalau tidak dimanfaatkan.",
    "Ingat, hasil akhir ditentukan dari seberapa keras kamu bertahan.",
    "Masih ada peluang besar di depan. Rebut dengan usaha!",
    "Tunjukkan bahwa kamu lebih tangguh dari masalahmu.",
    "Jangan tunggu motivasi, ciptakan motivasi dari tindakanmu sendiri.",
    "Kalau bukan kamu yang ubah nasibmu, siapa lagi?",
    "Setiap detik kamu tunda, adalah jarak yang makin jauh dari impianmu.",
    "Kamu masih bisa, selama kamu mau bergerak.",
    "Hari ini adalah panggungmu untuk membalik keadaan.",
    "Rasa lelah boleh, tapi menyerah bukan pilihan.",
    "Ingat, setiap usaha hari ini adalah cerita bangga besok.",
    "Semangatmu hari ini adalah modal untuk masa depanmu.",
    "Bangun semangatmu seperti kamu membangun masa depan orang yang kamu sayangi.",
]
