# Generated by Django 5.2.1 on 2025-07-01 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0005_product_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryImportStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_time', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_inbound', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_outbound', models.CharField(max_length=100, unique=True)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_supplier', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('kota', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inbound')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRakInboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('waktu_input', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('inbound_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inbounditem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('rak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.rak')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpnameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_opname', models.DateTimeField(auto_now_add=True)),
                ('qty_fisik', models.IntegerField()),
                ('qty_sistem', models.IntegerField()),
                ('selisih', models.IntegerField()),
                ('catatan', models.TextField(blank=True, default='')),
                ('petugas_opname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.outbound')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('quantity_locked', models.IntegerField(default=0)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='inbound',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='InventoryRakStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('rak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.rak')),
            ],
            options={
                'unique_together': {('product', 'rak')},
            },
        ),
        migrations.CreateModel(
            name='OpnameQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(blank=True, default='', max_length=100)),
                ('terakhir_opname', models.DateTimeField(blank=True, null=True)),
                ('prioritas', models.IntegerField(default=10)),
                ('sumber_prioritas', models.CharField(default='cycle_count', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=20)),
                ('ditambahkan_pada', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'unique_together': {('product', 'status')},
            },
        ),
        migrations.CreateModel(
            name='StockCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipe_pergerakan', models.CharField(choices=[('inbound', 'Inbound (+)'), ('reverse_inbound', 'Reverse Inbound (-)'), ('outbound', 'Outbound (-)'), ('reverse_outbound', 'Reverse Outbound (+)'), ('opname_in', 'Opname In (+)'), ('opname_out', 'Opname Out (-)'), ('kunci_stok', 'Kunci Stok (Batch) (-)'), ('reopen_batch', 'Batal Kunci Stok (Re-Open) (+)'), ('close_batch', 'Close Batch (-)'), ('reverse_batch', 'Reverse Batch (+)'), ('return_stock', 'Return Stock (+)'), ('reject_stock', 'Reject Stock (-)'), ('pindah_rak', 'Pindah Rak'), ('pindah_gudang', 'Pindah Gudang'), ('koreksi_stok', 'Koreksi Stok (+/-)')], max_length=30)),
                ('qty', models.IntegerField()),
                ('qty_awal', models.IntegerField()),
                ('qty_akhir', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], db_index=True, default='active', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kartu_stok', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='inventory_s_content_cb56f8_idx')],
            },
        ),
    ]
