# Generated by Django 5.2.2 on 2025-06-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_locked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_ready',
            field=models.IntegerField(default=0),
        ),
    ]
