# Generated by Django 5.2.2 on 2025-08-04 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
        ('products', '0008_productaddhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbounditem',
            name='outbound',
        ),
        migrations.RemoveField(
            model_name='outbounditem',
            name='product',
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_putaway',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InventoryRakStockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_pergerakan', models.CharField(choices=[('putaway_masuk', 'Putaway Masuk (+)'), ('picking_keluar', 'Picking Keluar (-)'), ('transfer_masuk', 'Transfer Masuk (+)'), ('transfer_keluar', 'Transfer Keluar (-)'), ('koreksi', 'Koreksi Stok (+/-)'), ('return_masuk', 'Return Masuk (+)'), ('return_keluar', 'Return Keluar (-)')], max_length=20)),
                ('jumlah', models.IntegerField()),
                ('jumlah_awal', models.IntegerField()),
                ('jumlah_akhir', models.IntegerField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('waktu_buat', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('rak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.rak')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu_buat'],
            },
        ),
        migrations.DeleteModel(
            name='Outbound',
        ),
        migrations.DeleteModel(
            name='OutboundItem',
        ),
        migrations.AddIndex(
            model_name='inventoryrakstocklog',
            index=models.Index(fields=['content_type', 'object_id'], name='inventory_i_content_a22662_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrakstocklog',
            index=models.Index(fields=['produk', 'rak'], name='inventory_i_produk__e25e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrakstocklog',
            index=models.Index(fields=['waktu_buat'], name='inventory_i_waktu_b_1e437b_idx'),
        ),
    ]
