# Generated by Django 5.2.2 on 2025-08-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_outbounditem_outbound_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryrakstocklog',
            old_name='jumlah',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='inventoryrakstocklog',
            old_name='jumlah_akhir',
            new_name='qty_akhir',
        ),
        migrations.RenameField(
            model_name='inventoryrakstocklog',
            old_name='jumlah_awal',
            new_name='qty_awal',
        ),
    ]
