# Generated by ChatGPT on 2025-06-06
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0002_stock_quantity_locked_stock_quantity_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryImportStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_time', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.CharField(max_length=100, blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
            ],
        ),
    ]
