# Generated by Django 5.2.2 on 2025-08-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_jumlah_inventoryrakstocklog_qty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryRakInboundItem',
        ),
    ]
