# Generated by Django 5.2.2 on 2025-06-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_historyimportstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
