# Generated by Django 5.2.2 on 2025-08-06 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventory_rak_inbound_item'),
        ('products', '0008_productaddhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RakOpnameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50, unique=True)),
                ('tanggal_mulai', models.DateTimeField(auto_now_add=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'Sedang Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opname_sessions_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opname_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('rak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.rak')),
            ],
            options={
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='RakTransferSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50, unique=True)),
                ('tanggal_transfer', models.DateTimeField(auto_now_add=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'Sedang Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_sessions_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('rak_asal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='products.rak')),
                ('rak_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='products.rak')),
            ],
            options={
                'ordering': ['-tanggal_transfer'],
            },
        ),
        migrations.CreateModel(
            name='RakOpnameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_sistem', models.IntegerField()),
                ('qty_fisik', models.IntegerField(blank=True, null=True)),
                ('qty_selisih', models.IntegerField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.rakopnamesession')),
            ],
            options={
                'ordering': ['product__nama_produk'],
                'unique_together': {('session', 'product')},
            },
        ),
        migrations.CreateModel(
            name='RakTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_transfer', models.IntegerField()),
                ('qty_asal_sebelum', models.IntegerField()),
                ('qty_asal_sesudah', models.IntegerField()),
                ('qty_tujuan_sebelum', models.IntegerField()),
                ('qty_tujuan_sesudah', models.IntegerField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.raktransfersession')),
            ],
            options={
                'ordering': ['product__nama_produk'],
                'unique_together': {('session', 'product')},
            },
        ),
    ]
