# Generated by Django 5.2.1 on 2025-06-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inbound_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
