# Generated by Django 5.2.2 on 2025-08-07 03:42

from django.db import migrations, models
import django.db.models.deletion


def migrate_rak_data(apps, schema_editor):
    """
    Memindahkan data rak dari products_rak ke inventory_rak
    """
    # Get the old and new models
    OldRak = apps.get_model('products', 'Rak')
    NewRak = apps.get_model('inventory', 'Rak')
    
    # Copy all rak data
    for old_rak in OldRak.objects.all():
        NewRak.objects.create(
            id=old_rak.id,  # Preserve the ID
            kode_rak=old_rak.kode_rak,
            nama_rak=old_rak.nama_rak,
            panjang_cm=old_rak.panjang_cm,
            lebar_cm=old_rak.lebar_cm,
            tinggi_cm=old_rak.tinggi_cm,
            kapasitas_kg=old_rak.kapasitas_kg,
            lokasi=old_rak.lokasi,
            keterangan=old_rak.keterangan,
            created_at=old_rak.created_at,
        )


def reverse_migrate_rak_data(apps, schema_editor):
    """
    Reverse migration - memindahkan data kembali ke products_rak
    """
    # Get the old and new models
    OldRak = apps.get_model('products', 'Rak')
    NewRak = apps.get_model('inventory', 'Rak')
    
    # Copy all rak data back
    for new_rak in NewRak.objects.all():
        OldRak.objects.create(
            id=new_rak.id,  # Preserve the ID
            kode_rak=new_rak.kode_rak,
            nama_rak=new_rak.nama_rak,
            panjang_cm=new_rak.panjang_cm,
            lebar_cm=new_rak.lebar_cm,
            tinggi_cm=new_rak.tinggi_cm,
            kapasitas_kg=new_rak.kapasitas_kg,
            lokasi=new_rak.lokasi,
            keterangan=new_rak.keterangan,
            created_at=new_rak.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rakopnamesession_raktransfersession_rakopnameitem_and_more'),
    ]

    operations = [
        # 1. Create the new Rak model in inventory
        migrations.CreateModel(
            name='Rak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_rak', models.CharField(max_length=20, unique=True)),
                ('nama_rak', models.CharField(max_length=100)),
                ('panjang_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lebar_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tinggi_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('kapasitas_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_rak',
            },
        ),
        # 2. Migrate data from products.Rak to inventory.Rak
        migrations.RunPython(migrate_rak_data, reverse_migrate_rak_data),
    ]
