# Generated by Django 5.2.2 on 2025-08-07 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_create_rak_model'),
    ]

    operations = [
        # Update foreign keys to point to inventory.Rak instead of products.Rak
        migrations.AlterField(
            model_name='inventoryrakstock',
            name='rak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rak'),
        ),
        migrations.AlterField(
            model_name='inventoryrakstocklog',
            name='rak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rak'),
        ),
        migrations.AlterField(
            model_name='rakopnamesession',
            name='rak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rak'),
        ),
        migrations.AlterField(
            model_name='raktransfersession',
            name='rak_asal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='inventory.rak'),
        ),
        migrations.AlterField(
            model_name='raktransfersession',
            name='rak_tujuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='inventory.rak'),
        ),
    ]
