# Generated by Django 5.2.2 on 2025-08-07 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_update_foreign_keys'),
        ('products', '0011_editproductlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpnameRak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('done', 'Selesai'), ('cancel', 'Batal')], default='draft', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('rak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rak')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpnameRakItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_fisik', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_sistem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selisih', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('opname_rak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.opnamerak')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OpnameRakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel')], max_length=20)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('opname_rak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.opnamerak')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
