# Generated by Django 5.2.2 on 2025-08-07 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_opnamerak_opnamerakitem_opnameraklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opnamerakitem',
            name='opname_rak',
        ),
        migrations.RemoveField(
            model_name='opnameraklog',
            name='opname_rak',
        ),
        migrations.RemoveField(
            model_name='opnamerakitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='opnameraklog',
            name='user',
        ),
        migrations.AlterField(
            model_name='rakopnamesession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'Sedang Berlangsung'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='RakOpnameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Buat Sesi'), ('add_item', 'Tambah Item'), ('update_item', 'Update Item'), ('delete_item', 'Hapus Item'), ('selesai', 'Selesai Opname'), ('batal', 'Batalkan Opname')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.rakopnamesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='OpnameRak',
        ),
        migrations.DeleteModel(
            name='OpnameRakItem',
        ),
        migrations.DeleteModel(
            name='OpnameRakLog',
        ),
    ]
