# Generated by Django 5.2.2 on 2025-08-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_opnamerakitem_opname_rak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rak',
            name='barcode_rak',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='raktransfersession',
            name='mode',
            field=models.CharField(choices=[('direct', 'Transfer Langsung'), ('transfer_putaway', 'Transfer Putaway')], default='direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryrakstocklog',
            name='tipe_pergerakan',
            field=models.CharField(choices=[('putaway_masuk', 'Putaway Masuk (+)'), ('picking_keluar', 'Picking Keluar (-)'), ('transfer_masuk', 'Transfer Rak Masuk (+)'), ('transfer_keluar', 'Transfer Rak Keluar (-)'), ('koreksi', 'Koreksi Stok (+/-)'), ('return_masuk', 'Return Masuk (+)'), ('return_keluar', 'Return Keluar (-)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='raktransfersession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'Sedang Berlangsung'), ('ready_for_putaway', 'Siap Putaway'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='draft', max_length=20),
        ),
    ]
