# Generated by Django 5.2.2 on 2025-08-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rak_barcode_rak_raktransfersession_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrakstock',
            name='quantity_opname',
            field=models.IntegerField(default=0),
        ),
    ]
