# Generated by Django 5.2.2 on 2025-08-11 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventoryrakstock_quantity_opname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FullOpnameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50, unique=True)),
                ('nama_opname', models.CharField(max_length=200)),
                ('tanggal_mulai', models.DateTimeField(auto_now_add=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'Sedang Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_opname_sessions_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_opname_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_opname_sessions_supervised', to=settings.AUTH_USER_MODEL)),
                ('target_raks', models.ManyToManyField(blank=True, related_name='full_opname_sessions', to='inventory.rak')),
            ],
            options={
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.AddField(
            model_name='rakopnamesession',
            name='full_opname_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rak_opname_sessions', to='inventory.fullopnamesession'),
        ),
    ]
