# Generated by Django 5.2.2 on 2025-08-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_fullopnamesession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakopnamesession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('selesai', 'Completed'), ('dibatalkan', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
