# Generated by Django 5.2.1 on 2025-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_rakopnamesession_status'),
        ('products', '0014_add_database_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryrakstock',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='inventoryrakstock',
            index=models.Index(fields=['product'], name='inventory_i_product_6e899b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrakstock',
            index=models.Index(fields=['rak'], name='inventory_i_rak_id_de0e76_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrakstock',
            index=models.Index(fields=['product', 'rak'], name='inventory_i_product_6aa05d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrakstock',
            index=models.Index(fields=['updated_at'], name='inventory_i_updated_3bfbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sku'], name='inventory_s_sku_26398e_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product'], name='inventory_s_product_4c1da7_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sku', 'quantity'], name='inventory_s_sku_91935e_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'quantity_locked'], name='inventory_s_product_db7750_idx'),
        ),
    ]
