# Generated by Django 5.2.2 on 2025-08-23 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_database_indexes'),
        ('products', '0015_remove_product_products_pr_barcode_e44f4f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PutawaySlottingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('putaway_time', models.DateTimeField(auto_now_add=True)),
                ('is_auto', models.BooleanField(default=False, help_text='True jika slotting dilakukan otomatis oleh sistem')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Putaway Slotting Log',
                'verbose_name_plural': 'Putaway Slotting Logs',
                'ordering': ['-putaway_time'],
            },
        ),
        migrations.RemoveIndex(
            model_name='inventoryrakstock',
            name='inventory_i_product_6e899b_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryrakstock',
            name='inventory_i_rak_id_de0e76_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryrakstock',
            name='inventory_i_product_6aa05d_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryrakstock',
            name='inventory_i_updated_3bfbd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='inventory_s_sku_26398e_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='inventory_s_product_4c1da7_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='inventory_s_sku_91935e_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='inventory_s_product_db7750_idx',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryrakstock',
            unique_together={('product', 'rak')},
        ),
        migrations.AddField(
            model_name='putawayslottinglog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='putawayslottinglog',
            name='putaway_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='putawayslottinglog',
            name='rak_tujuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rak'),
        ),
        migrations.AddField(
            model_name='putawayslottinglog',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stock'),
        ),
    ]
