# Generated by Django 5.2.2 on 2025-08-23 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_putawayslottinglog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='putaway_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Putaway By'),
        ),
        migrations.AddField(
            model_name='stock',
            name='putaway_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Putaway Time'),
        ),
        migrations.AddField(
            model_name='stock',
            name='rak_tujuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rak', verbose_name='Rak Tujuan'),
        ),
    ]
