# Generated by Django 5.2.2 on 2025-08-24 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_slotting_fields_to_stock'),
        ('products', '0015_remove_product_products_pr_barcode_e44f4f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='putawayslottinglog',
            old_name='rak_tujuan',
            new_name='suggested_rak',
        ),
        migrations.RemoveField(
            model_name='putawayslottinglog',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='rak_tujuan',
        ),
        migrations.CreateModel(
            name='Putaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('putaway_time', models.DateTimeField(blank=True, null=True, verbose_name='Putaway Time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('slotted', 'Slotted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='putaway_items', to='products.product')),
                ('putaway_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Putaway By')),
                ('suggested_rak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rak', verbose_name='Suggested Rak')),
            ],
            options={
                'verbose_name': 'Putaway Item',
                'verbose_name_plural': 'Putaway Items',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'status')},
            },
        ),
        migrations.AddField(
            model_name='putawayslottinglog',
            name='putaway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slotting_logs', to='inventory.putaway'),
        ),
        migrations.CreateModel(
            name='RakCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_front', models.DecimalField(decimal_places=2, default=0, help_text='Front space yang masih tersedia (cm)', max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rak', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='inventory.rak')),
            ],
            options={
                'verbose_name': 'Rak Capacity',
                'verbose_name_plural': 'Rak Capacities',
            },
        ),
    ]
