# Generated by Django 5.2.1 on 2025-08-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_rename_rak_tujuan_putawayslottinglog_suggested_rak_and_more'),
        ('products', '0015_remove_product_products_pr_barcode_e44f4f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryrakstock',
            index=models.Index(fields=['rak', 'quantity'], name='inventory_i_rak_id_5fbfc1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrakstock',
            index=models.Index(fields=['quantity'], name='inventory_i_quantit_bac6a6_idx'),
        ),
    ]
