# Generated by Django 5.2.2 on 2025-08-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_inventory_rak_stock_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putawayslottinglog',
            name='putaway',
        ),
        migrations.DeleteModel(
            name='Putaway',
        ),
    ]
