# Generated by Django 5.2.2 on 2025-08-27 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_putaway_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='suggested_rak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rak', verbose_name='Suggested Rak'),
        ),
    ]
