# Generated by Django 5.2.2 on 2025-08-27 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_add_suggested_rak_to_stock'),
        ('products', '0015_remove_product_products_pr_barcode_e44f4f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='suggested_rak',
        ),
        migrations.CreateModel(
            name='Putaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('putaway_time', models.DateTimeField(blank=True, null=True, verbose_name='Putaway Time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='putaway_items', to='products.product')),
                ('putaway_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Putaway By')),
                ('suggested_rak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rak', verbose_name='Suggested Rak')),
            ],
            options={
                'verbose_name': 'Putaway',
                'verbose_name_plural': 'Putaways',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='putawayslottinglog',
            name='putaway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slotting_logs', to='inventory.putaway'),
        ),
    ]
