# Generated by Django 5.2.2 on 2025-08-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_restore_putaway_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity_putaway',
        ),
    ]
