# Generated by Django 5.2.1 on 2025-08-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_stock_quantity_putaway'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_putaway',
            field=models.IntegerField(default=0),
        ),
    ]
