# Generated by Django 5.2.1 on 2025-08-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_stock_quantity_putaway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putawayslottinglog',
            name='putaway',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='putaway_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='putaway_time',
        ),
        migrations.DeleteModel(
            name='Putaway',
        ),
    ]
