# Generated by Django 5.2.1 on 2025-08-27 04:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_putawayslottinglog_putaway_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='putawayslottinglog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Putaway Slotting Log', 'verbose_name_plural': 'Putaway Slotting Logs'},
        ),
        migrations.RemoveField(
            model_name='putawayslottinglog',
            name='is_auto',
        ),
        migrations.RemoveField(
            model_name='putawayslottinglog',
            name='notes',
        ),
        migrations.AddField(
            model_name='putawayslottinglog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='putawayslottinglog',
            name='putaway_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='putawayslottinglog',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='putawayslottinglog',
            name='suggested_rak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.rak'),
        ),
    ]
