# Generated by Django 5.2.1 on 2025-08-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_putawayslottinglog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rak',
            name='lokasi',
            field=models.CharField(blank=True, choices=[('DEKAT', 'DEKAT'), ('SEDANG', 'SEDANG'), ('JAUH', 'JAUH'), ('BEDA_GUDANG', 'BEDA GUDANG')], help_text='Prioritas slotting: DEKAT (tinggi) → BEDA GUDANG (rendah)', max_length=20, null=True),
        ),
    ]
