# Generated by Django 5.2.1 on 2025-08-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_rak_lokasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='putawayslottinglog',
            name='notes',
            field=models.TextField(blank=True, help_text='Catatan slotting/putaway', null=True),
        ),
    ]
