# Generated by Django 5.2.2 on 2025-09-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_add_notes_to_putawayslottinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='putaway_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp terakhir kali ada item yang di-putaway', null=True),
        ),
    ]
