# Generated by Django 5.2.2 on 2025-09-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_stock_putaway_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='putaway_at',
        ),
    ]
