# Generated by Django 5.2.2 on 2025-10-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_stock_putaway_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rakopnamesession',
            name='tipe_session',
            field=models.CharField(choices=[('full_opname', 'Full Opname'), ('reguler_opname', 'Reguler Opname'), ('partial_opname', 'Partial Opname')], default='reguler_opname', help_text='Tipe sesi opname: Full Opname (semua rak), Reguler Opname (1 rak), Partial Opname (pilih produk)', max_length=20),
        ),
    ]
