# Generated by Django 5.2.1 on 2025-10-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_inbound_po_inbound_received_at_inbound_received_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound',
            name='supplier',
        ),
        migrations.AddField(
            model_name='inbound',
            name='from_rak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='inventory.rak'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='to_rak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='inventory.rak'),
        ),
    ]
