# Generated by Django 5.2.1 on 2025-10-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_change_inbound_to_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound',
            name='from_rak',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='to_rak',
        ),
        migrations.AddField(
            model_name='inbound',
            name='from_warehouse',
            field=models.CharField(blank=True, help_text='Gudang asal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inbound',
            name='to_warehouse',
            field=models.CharField(blank=True, help_text='Gudang tujuan', max_length=100, null=True),
        ),
    ]
