# Generated by Django 5.2.1 on 2025-10-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_remove_inbound_from_rak_remove_inbound_to_rak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcardentry',
            name='tipe_pergerakan',
            field=models.CharField(choices=[('inbound', 'Inbound (+)'), ('reverse_inbound', 'Reverse Inbound (-)'), ('purchase', 'Purchase (+)'), ('outbound', 'Outbound (-)'), ('reverse_outbound', 'Reverse Outbound (+)'), ('opname_in', 'Opname In (+)'), ('opname_out', 'Opname Out (-)'), ('kunci_stok', 'Kunci Stok (Batch) (-)'), ('reopen_batch', 'Batal Kunci Stok (Re-Open) (+)'), ('close_batch', 'Close Batch (-)'), ('reverse_batch', 'Reverse Batch (+)'), ('return_stock', 'Return Stock (+)'), ('reject_stock', 'Reject Stock (-)'), ('pindah_rak', 'Pindah Rak'), ('pindah_gudang', 'Pindah Gudang'), ('koreksi_stok', 'Koreksi Stok (+/-)')], max_length=30),
        ),
    ]
