# Generated by Django 5.2.2 on 2025-11-01 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_stockcardentry_tipe_pergerakan'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
