# Generated by Django 5.2.1 on 2025-10-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchase_purchaseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
