# Generated by Django 5.2.1 on 2025-10-18 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_remove_inbound_from_rak_remove_inbound_to_rak_and_more'),
        ('purchasing', '0004_alter_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
    ]
