# Generated by Django 5.2.1 on 2025-10-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_alter_purchase_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('received', 'Received')], default='draft', max_length=20),
        ),
    ]
