# Generated by Django 5.2.1 on 2025-10-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
