# Generated by Django 5.2.1 on 2025-10-19 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_pricehistory_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='purchasing.purchase'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='purchasing.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='purchasing.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='purchasing.purchaseorderitem'),
        ),
    ]
