# Generated by Django 5.2.1 on 2025-10-19 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_stockcardentry_tipe_pergerakan'),
        ('purchasing', '0009_pricehistory_purchase_pricehistory_purchase_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('transfer', 'Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='purchasing.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Payment',
                'verbose_name_plural': 'Purchase Payments',
                'ordering': ['-due_date'],
                'indexes': [models.Index(fields=['status', '-due_date'], name='purchasing__status_7dacbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseTaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=11, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='tax_invoices/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_invoice', to='purchasing.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Tax Invoice',
                'verbose_name_plural': 'Purchase Tax Invoices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='purchasing__status_5bf899_idx')],
            },
        ),
    ]
