# Generated by Django 5.2.2 on 2025-10-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0013_purchase_verified_at_purchase_verified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='harga_beli',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='harga_beli',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
