# Generated by Django 5.2.2 on 2025-10-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0014_alter_purchase_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasetaxinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
