# Generated by Django 5.2.2 on 2025-10-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0015_purchasepayment_discount_purchasetaxinvoice_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='remaining_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasepaymentallocation',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasetaxinvoice',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasetaxinvoice',
            name='invoice_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasetaxinvoice',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasetaxinvoice',
            name='tax_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasetaxinvoice',
            name='tax_rate',
            field=models.IntegerField(default=11),
        ),
    ]
