# Generated by Django 5.2.1 on 2025-10-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0016_alter_purchasepayment_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='nomor_purchase',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
