# Generated by Django 5.2.1 on 2025-10-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0017_make_nomor_purchase_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='nomor_po',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
