# Generated by Django 5.2.1 on 2025-10-21 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0018_make_nomor_po_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-tanggal_purchase', '-id'], 'permissions': [('purchase_view', 'Can view Purchase'), ('purchase_warehouse', 'Can create/edit/receive Purchase (Warehouse)'), ('purchase_finance', 'Can verify/payment/tax invoice Purchase (Finance)')], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-tanggal_po', '-id'], 'permissions': [('po_view', 'Can view Purchase Order'), ('po_marketing', 'Can create/edit Purchase Order (Marketing)')], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
    ]
