# Generated by Django 5.2.1 on 2025-10-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0019_alter_purchase_options_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='transaction_type',
            field=models.CharField(choices=[('COD', 'COD (Cash on Delivery)'), ('CREDIT', 'Credit'), ('PREPAID', 'Prepaid')], default='CREDIT', help_text='Tipe transaksi pembayaran', max_length=50),
        ),
    ]
