# Generated by Django 5.2.1 on 2025-10-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0020_purchasepayment_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='tanggal_purchase',
            field=models.DateTimeField(blank=True, help_text='Tanggal invoice dari supplier (user harus isi manual)', null=True),
        ),
    ]
