# Generated by Django 5.2.1 on 2025-10-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0021_alter_purchase_tanggal_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='tanggal_purchase',
            field=models.DateField(blank=True, help_text='Tanggal invoice dari supplier (user harus isi manual)', null=True),
        ),
    ]
