# Generated by Django 5.2.1 on 2025-10-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0022_change_tanggal_purchase_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
