# Generated by Django 5.2.2 on 2025-10-22 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('purchasing', '0023_change_purchase_date_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Link ke akun di Chart of Accounts untuk pencatatan akuntansi', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banks', to='finance.account'),
        ),
    ]
