# Generated by Django 5.2.2 on 2025-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0024_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='account',
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tanggal_purchase',
            field=models.DateTimeField(blank=True, help_text='Tanggal invoice dari supplier (user harus isi manual)', null=True),
        ),
    ]
