# Generated by Django 5.2.2 on 2025-10-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0024_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='has_tax_invoice',
            field=models.BooleanField(default=True, help_text='Dapat Faktur Pajak? (default: Ya)'),
        ),
    ]
