# Generated by Django 5.2.2 on 2025-10-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0025_purchase_has_tax_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='has_tax_invoice',
            field=models.BooleanField(default=False, help_text='Dapat Faktur Pajak? (pilih saat verifikasi)'),
        ),
    ]
