"""
Django settings for erp_alfa project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print(f"DEBUG: BASE_DIR is {BASE_DIR}")
print(f"DEBUG: STATICFILES_DIRS[0] is {os.path.join(BASE_DIR, 'static')}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s&efx(f9_)70+@7^ev459#$ahvs6%*b&r8#1%0!+g#c!)wsaow'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.68.111',
    'erp.local',
    'alfaerp.id',
    'www.alfaerp.id',
    '*',  # Allow all hosts for development
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'products',
    'orders',
    'inventory',
    'fullfilment',
    'accounts.apps.AccountsConfig',
    'django_tables2',
    'django_filters',
    'django_extensions',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'erp_alfa.middleware.SessionExpiryMessageMiddleware',
]

ROOT_URLCONF = 'erp_alfa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'erp_alfa.wsgi.application'

ASGI_APPLICATION = 'erp_alfa.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'alfa.erp',
        'USER': 'vialli',
        'PASSWORD': '123212345',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'id-id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'  # Tambahkan forward slash

# Direktori tempat Django akan mencari file statis tambahan
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Direktori tempat file statis dikumpulkan saat deploy (python manage.py collectstatic)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (Product Images, etc)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Gunakan os.path.join untuk konsistensi

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery settings
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/server.log',
        },
    },
    'loggers': {
        'extract_sku_debug': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Konfigurasi Channel Layers
# Contoh menggunakan in-memory channel layer (untuk development/testing sederhana)
# Untuk produksi, sebaiknya pakai Redis
if DEBUG:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("127.0.0.1", 6379)],
            },
        },
    }

# Jika kamu ingin pakai Redis (direkomendasikan untuk produksi):
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)], # Sesuaikan dengan host dan port Redis kamu
#         },
#     },
# }

# Ubah nilai ini untuk menaikkan batas ukuran upload file
# Defaultnya 2.5 MB (2621440 bytes)
# Contoh: Untuk 10 MB
# DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760 # 10 MB
# FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760 # 10 MB

# Untuk 100 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600 # 100 MB (100 * 1024 * 1024)
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600 # 100 MB (100 * 1024 * 1024)

# Session hanya bertahan 8 jam (dalam detik)
SESSION_COOKIE_AGE =  28800 # 8 jam = 8*60*60 detik
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session tidak hilang saat browser ditutup, hanya saat 8 jam lewat

LOGIN_URL = '/login/' # Sesuaikan dengan URL login Anda
LOGIN_REDIRECT_URL = '/'  # Setelah login, redirect ke halaman utama
LOGOUT_REDIRECT_URL = '/login/'  # Setelah logout, redirect ke login

HANDLER403 = 'erp_alfa.views.custom_permission_denied_view'

# CSRF Settings for tunnel access and domain
CSRF_TRUSTED_ORIGINS = [
    'https://alfaerp.id',
    'https://www.alfaerp.id',
    'https://eewvqzetol.a.pinggy.link',
    'https://*.pinggy.link',
    'https://*.a.pinggy.link',
    'https://*.ngrok.io',
    'https://*.ngrok-free.app',
]

# Additional CSRF settings for development
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False
