# Generated by Django 5.2.1 on 2025-06-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoextract',
            name='id_pesanan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoextract',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
