# Generated by Django 5.2.1 on 2025-06-13 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_demoextract_id_pesanan_demoextract_status'),
        ('products', '0003_productsbundling'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoextract',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='demoextract',
            name='status_bundle',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
