# Generated by Django 5.2.1 on 2025-06-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_demoextract_product_demoextract_status_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoextract',
            name='status_order',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
