# Generated by Django 5.2.1 on 2025-06-13 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productsbundling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_customer', models.CharField(max_length=255)),
                ('alamat_cust', models.TextField(blank=True, null=True)),
                ('kota', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='normal', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCukup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pesanan', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTidakCukup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pesanan', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembuatan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_pesanan', models.CharField(blank=True, max_length=50, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_toko', models.CharField(blank=True, max_length=100, null=True)),
                ('id_pesanan', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('jumlah', models.IntegerField(default=0)),
                ('harga_promosi', models.FloatField(blank=True, null=True)),
                ('catatan_pembeli', models.TextField(blank=True, null=True)),
                ('kurir', models.CharField(blank=True, max_length=100, null=True)),
                ('awb_no_tracking', models.CharField(blank=True, max_length=100, null=True)),
                ('metode_pengiriman', models.CharField(blank=True, max_length=100, null=True)),
                ('kirim_sebelum', models.CharField(blank=True, max_length=100, null=True)),
                ('order_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status_order', models.CharField(blank=True, max_length=50, null=True)),
                ('status_cancel', models.CharField(blank=True, max_length=50, null=True)),
                ('status_retur', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_batch', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah_ambil', models.IntegerField(default=0)),
                ('status_ambil', models.CharField(blank=True, max_length=50, null=True)),
                ('status_stock', models.CharField(blank=True, max_length=50, null=True)),
                ('status_bundle', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHandoverHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_ho', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_time', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='import_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.orderimporthistory'),
        ),
        migrations.CreateModel(
            name='OrderPackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_pack', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPrintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_print', models.DateTimeField(auto_now_add=True)),
                ('status_print', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pesanan', models.CharField(db_index=True, max_length=100, unique=True)),
                ('tanggal_pembuatan', models.DateTimeField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_lists', to='orders.customer')),
            ],
            options={
                'db_table': 'orders_orderlist',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['id_pesanan'], name='orders_orde_id_pesa_afafd9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sku'], name='orders_orde_sku_e0993e_idx'),
        ),
    ]
