# Generated by Django 5.2.1 on 2025-06-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersextracthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdersExtractHistory',
        ),
    ]
