# Generated by Django 5.2.2 on 2025-08-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordershippinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippinghistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
