# Generated by Django 5.2.1 on 2025-09-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ordershippinghistory_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_access_checking', 'Can access checking module (order-checking-list and scanpicking)')]},
        ),
        migrations.AlterModelOptions(
            name='orderpackinghistory',
            options={'permissions': [('can_access_packing', 'Can access packing module (order-packing-list and scanpacking)')]},
        ),
        migrations.AlterModelOptions(
            name='ordershippinghistory',
            options={'permissions': [('can_access_shipping', 'Can access shipping module (order-shipping-list and scanshipping)')]},
        ),
    ]
