# Generated by Django 5.2.1 on 2025-10-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderpackinghistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ordershippinghistory',
            options={},
        ),
    ]
