# Generated by Django 5.2.1 on 2025-06-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimporthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsBundling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_bundling', models.CharField(max_length=100, unique=True)),
                ('sku_list', models.TextField(help_text='Daftar SKU dipisahkan koma, contoh: SKU1,SKU2,SKU3')),
            ],
        ),
    ]
