# Generated by Django 5.2.1 on 2025-06-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsbundling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_rak', models.CharField(max_length=20, unique=True)),
                ('nama_rak', models.CharField(max_length=100)),
                ('panjang_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lebar_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tinggi_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('kapasitas_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products_rak',
            },
        ),
    ]
