# Generated by Django 5.2.2 on 2025-08-07 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productaddhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rak',
        ),
    ]
