# Generated by Django 5.2.1 on 2025-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_rak_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='berat_gram',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Berat produk dalam gram', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lebar_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lebar produk dalam cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='panjang_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Panjang produk dalam cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tinggi_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tinggi produk dalam cm', max_digits=8, null=True),
        ),
    ]
