# Generated by Django 5.2.1 on 2025-08-07 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_berat_gram_product_lebar_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(help_text='Nama field yang berubah', max_length=50)),
                ('old_value', models.TextField(blank=True, help_text='Nilai lama', null=True)),
                ('new_value', models.TextField(blank=True, help_text='Nilai baru', null=True)),
                ('change_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='UPDATE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan', null=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Edit Log',
                'verbose_name_plural': 'Product Edit Logs',
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['product', '-edited_at'], name='products_ed_product_afd411_idx'), models.Index(fields=['edited_by', '-edited_at'], name='products_ed_edited__79fb62_idx'), models.Index(fields=['field_name'], name='products_ed_field_n_3d8ad9_idx')],
            },
        ),
    ]
