# Generated by Django 5.2.2 on 2025-08-18 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_editproductlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='editproductlog',
            name='product_barcode',
            field=models.CharField(blank=True, help_text='Barcode produk (untuk produk yang sudah dihapus)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='editproductlog',
            name='product_name',
            field=models.CharField(blank=True, help_text='Nama produk (untuk produk yang sudah dihapus)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='editproductlog',
            name='product_sku',
            field=models.CharField(blank=True, help_text='SKU produk (untuk produk yang sudah dihapus)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='editproductlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='editproductlog',
            index=models.Index(fields=['product_sku'], name='products_ed_product_66f7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='editproductlog',
            index=models.Index(fields=['change_type'], name='products_ed_change__b0ea87_idx'),
        ),
    ]
