# Generated by Django 5.2.1 on 2025-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_populate_product_info'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='products_pr_barcode_e44f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rak'], name='products_pr_rak_ad2241_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['nama_produk', 'brand'], name='products_pr_nama_pr_4f35b3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku', 'is_active'], name='products_pr_sku_80897b_idx'),
        ),
        migrations.AddIndex(
            model_name='productextrabarcode',
            index=models.Index(fields=['barcode'], name='products_pr_barcode_43ee30_idx'),
        ),
        migrations.AddIndex(
            model_name='productextrabarcode',
            index=models.Index(fields=['product'], name='products_pr_product_2d23e2_idx'),
        ),
    ]
