# Generated by Django 5.2.2 on 2025-08-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_barcode_e44f4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_sku_ca0cdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_brand_4bfaa4_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_rak_ad2241_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_ca4d9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_nama_pr_4f35b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_sku_80897b_idx',
        ),
        migrations.RemoveIndex(
            model_name='productextrabarcode',
            name='products_pr_barcode_43ee30_idx',
        ),
        migrations.RemoveIndex(
            model_name='productextrabarcode',
            name='products_pr_product_2d23e2_idx',
        ),
    ]
