# Generated by Django 5.2.2 on 2025-08-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_products_pr_barcode_e44f4f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posisi_tidur',
            field=models.BooleanField(default=False, help_text='Bisa posisi tidur (hybrid stacking)'),
        ),
    ]
