# Generated by Django 5.2.1 on 2025-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_posisi_tidur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harga_beli',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga beli terakhir', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, help_text='Tanggal pembelian terakhir', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga beli dari pembelian terakhir', max_digits=12, null=True),
        ),
    ]
