# Generated by Django 5.2.2 on 2025-10-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_harga_beli_product_last_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hpp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga Pokok Penjualan (HPP) - Weighted Average', max_digits=12, null=True),
        ),
    ]
